### ISSUE TITLE
Autocomplete files and folders works depending on where you are

### ISSUE THREAD

**Issue by nemesiscodex** [shockone/black-screen#103]
Files and folders autocomplete using 'cd <kbd>Space</kbd>'
#### screenshots 
`~/bin/black-screen/`
![screenshot from 2015-09-09 00 50 45](https://cloud.githubusercontent.com/assets/3976562/9753598/12d5cac8-568d-11e5-8332-ab9da64790e1.png)
`~/`
![screenshot from 2015-09-09 00 51 20](https://cloud.githubusercontent.com/assets/3976562/9753599/12d93d34-568d-11e5-99e6-85a294580c8d.png)

**Comment by shockone** [comment]
Also can't reproduce on OS X. Does it happen for anybody else?

**Comment by joshtoo** [comment]
@shockone - Checking now

**Comment by G07cha** [comment]
Can't reproduce on OS X, @nemesiscodex, can you repeat again and define steps to reproduce?

**Comment by joshtoo** [comment]
@G07cha - I am wondering if he is trying to log a bug or request a feature. His issue can read either way.

**Comment by nemesiscodex** [comment]
>I am wondering if he is trying to log a bug or request a feature. His issue can read either way.

It's a bug, sorry about that. openSUSE 13.2

**Comment by G07cha** [comment]
Okay so it's probably Linux-specified problem, can someone check on another distributions to confirm this?

**Comment by mzgnr** [comment]
i can check fedora and ubuntu later today.

**Comment by joshtoo** [comment]
Confirmed on openSUSE 13.2, centOS 7 and Mint 17 running Cinnamon (64-bit)

**Comment by G07cha** [comment]
Ubuntu 14.04.2(trusty) works fine.
![screen shot 2015-09-09 at 5 39 47 pm](https://cloud.githubusercontent.com/assets/6943514/9764981/8a2de0be-571a-11e5-974e-b64035cfc4ce.png)

**Comment by shockone** [comment]
Should work now.
