### ISSUE TITLE
Pressing 'tab' moves your cursor to the front, and repeats the first suggestion every time

### ISSUE THREAD

**Issue by nemesiscodex** [shockone/black-screen#104]
![output](https://cloud.githubusercontent.com/assets/3976562/9754114/9ee6581a-5693-11e5-81e4-98c60abf3d5d.gif)

**Comment by shockone** [comment]
Cannot reproduce. I've created the same alias you have, but after I type `space`, I have a list of suggested directories, and autocompletion works as expected for them.

**Comment by nemesiscodex** [comment]
It happends with any command, same result with vim, clear, find, etc.
openSUSE 13.2, I just read that Linux is not supported :cry:

**Comment by joshtoo** [comment]
@nemesiscodex - Much like windows we are working on the *Nix bugs

**Comment by nemesiscodex** [comment]
:+1: 
something funny happened when I tried `ls` repeated many times
![screenshot from 2015-09-09 10 39 44](https://cloud.githubusercontent.com/assets/3976562/9764859/476e90ec-56df-11e5-8bb2-902e351dd18b.png)

**Comment by nemesiscodex** [comment]
> Much like windows we are working on the *Nix bugs

:+1:

**Comment by egladman** [comment]
I too can't reproduce, I'm on Arch Linux.

**Comment by anisimovt** [comment]
Same thing on OS X for me

**Comment by G07cha** [comment]
Reproduced for folders with spaces in name that relates to #78. Type `cd` select folder with space from drop-down list and press `Tab` key several times.

**Comment by esthor** [comment]
@G07cha I have the same issue when trying to 'cd' to folders with spaces...also, I can't figure out how to 'cd' into folders with spaces, even when typing it out. It only takes input until the first space in the path.

**Comment by brennebeck** [comment]
I just experienced the same on OSX 10.11. Typing a command and then tab completing it returns the cursor to the beginning of the line and additional tabs repeat the command, exactly like the the gif.
