### ISSUE TITLE
Extend Background on Multi-line Input 

### ISSUE THREAD

**Issue by draughoncollin** [shockone/black-screen#112]
The lighter grey that serves as the background for your command-line input should have multi-line functionality:
![screen shot 2015-09-09 at 6 40 55 am](https://cloud.githubusercontent.com/assets/6424040/9760783/c7b7d17c-56bd-11e5-846a-40b9c1497d16.png)

**Comment by draughoncollin** [comment]
Probably a related issue but putting in multiple multi-line inputs causes an overwrite of the next line:
![screen shot 2015-09-09 at 7 13 58 am](https://cloud.githubusercontent.com/assets/6424040/9761457/7743ac20-56c2-11e5-9112-8c552d9a3a8b.png)

**Comment by joshtoo** [comment]
True Story - OSX 10.11 Beta ( Not that this is going to be OS specific )
<img width="953" alt="screen shot 2015-09-09 at 7 17 23 am" src="https://cloud.githubusercontent.com/assets/8420490/9761522/df018a26-56c2-11e5-8166-1477af777e19.png">

**Comment by shockone** [comment]
Fixed. ![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/a771n893.png)
