### ISSUE TITLE
Tmux unusable

### ISSUE THREAD

**Issue by b4dtR1p** [shockone/black-screen#119]
unusable in ssh 
![schermata 2015-09-09 alle 23 04 53](https://cloud.githubusercontent.com/assets/2277780/9774354/3cbbe000-5748-11e5-9ee7-658c493c5249.png)
and also locally
![schermata 2015-09-09 alle 23 09 39](https://cloud.githubusercontent.com/assets/2277780/9774353/3cb9be92-5748-11e5-8c56-b1e57845de2e.png)

**Comment by draughoncollin** [comment]
@shockone if I'm correct, this would fall into the larger ssh scope. Should be tagged with ssh.

**Comment by shockone** [comment]
@draughoncollin it's related to ANSI sequences handling.

**Comment by shockone** [comment]
Fixed.
