### ISSUE TITLE
TrueColor (24 bit) color via escape sequences support

### ISSUE THREAD

**Issue by XVilka** [shockone/black-screen#139]
See all information about that here https://gist.github.com/XVilka/8346728

**Comment by onbjerg** [comment]
:+1:

**Comment by onbjerg** [comment]
Maybe this package could help? https://www.npmjs.com/package/ansi-to-html

**Comment by jerch** [comment]
The ansiparser only supports the semicolon notation, e.g. \x1b[38;2;0;0;0m
The discussed colon notation was introduced later and is not DEC compatible (left open for later specification in the original spec).

**Comment by shockone** [comment]
@XVilka, do you know any applications that use 24 bit colors?

**Comment by XVilka** [comment]
@shockone 

irssi - https://github.com/irssi/irssi/pull/48
neovim - https://github.com/neovim/neovim/commit/8dd415e887923f99ab5daaeba9f0303e173dd1aa
elinks - http://repo.or.cz/w/elinks.git/blob/HEAD:/configure.in#l1410 (./configure --enable-true-color)

**Comment by shockone** [comment]
@XVilka it was a stupid question, I should have read the link carefully. It does sound like a feature a modern terminal should have, thank you for the suggestion.

**Comment by shockone** [comment]
Added support in v0.0.32.
