### ISSUE TITLE
Set up Docker

### ISSUE THREAD

**Issue by shockone** [shockone/black-screen#15]
* Create a container which would have everything required for running specs and create an npm script `npm test` (see `package.json` for other scripts) to run those specs.

* Create a container which would have everything set up for new contributors to start working on the project. The goal is to make setup as easy as possible.

**Comment by jonadev95** [comment]
- So, I got my local copy of the repo, I mount it into the container and let the container do the test?
- That means all required tools and the up-to-date repo?

**Comment by shockone** [comment]
@jonadev95, that's the plan.

**Comment by jonadev95** [comment]
A little addition to the second point, so they should work inside the container?
I'll do it if you want :+1:

**Comment by shockone** [comment]
I don't have enough knowledge to answer that, but the goal is to make the development easy. I guess, it would be harder to work inside the container, right?

Please collaborate with @kblanks, he's also working on that.

**Comment by kblanks** [comment]
@jonadev95 I'm cool if you want to do this yourself, I'll find another issue to work on :+1:

**Comment by jonadev95** [comment]
@shockone depends, but a problem would be that it's possible to loose all of your work when accidentilly deleting the container. So better keep the code outside of it.

@kblanks thanks man :+1:   

I will start working on it.

**Comment by joshtoo** [comment]
@jonadev95 - Once we have an approved container, I will add the docker build / publish to Travis ( See #63 )

**Comment by jonadev95** [comment]
@joshtoo great! 
So someone will set up an account on hub.docker.com?

**Comment by G07cha** [comment]
@joshtoo, as I know Travis already run builds in dockers.

**Comment by jonadev95** [comment]
@G07cha If I understand it the right way, he means that he will add a job to build the dockerfiles and push them automatically to the docker hub repo

**Comment by G07cha** [comment]
Okay, I get it, but first of all we need to make black-screen stable build for Linux becouse all docker images are linux-based.

**Comment by jonadev95** [comment]
@G07cha I've tried it on my linux pc (Because I didn't see note that it's only for OS X ), and with gulp it works very well.

But if you think it's better to wait until it's stable I will write it based on the current state, but will wait for the stable release before opening a pull request.

**Comment by ruffsl** [comment]
This looks awesome. I've been playing with this project on Ubuntu, and aside from some "JavaScript error occurred in the main process" error popups, this looks promising. Have you thought of running the GUI interface within the container, using the host's Xserver with Unix sockets?

**Comment by jonadev95** [comment]
@ruffsl Do you mean the container which should run the tests? Or the one which isn't build yet to be like an sdk?

**Comment by jonadev95** [comment]
@ruffsl Yes if thought about it (And I've already used this workaround for myself), but IMO we should make shure that we don't affect the host in any way, 
and accept that there is a bigger overhead. I think we couldn't guarantee that with mounting system sockets and make a container privileged. 

But of course that's just my opinion, we should discuss it! :+1:

**Comment by ruffsl** [comment]
I'm new to this project, so I'm not sure of your question. I was thinking that if someone wanted to get started with a working dev environment, an also interactively run the app from the same container, this could be done. An example wiki I started in using GUI apps with docker:
http://wiki.ros.org/docker/Tutorials/GUI

There are ways doing this without elevating the container to privileged status though. This was the first project I found way back when that first did this:
https://github.com/sameersbn/docker-browser-box

**Comment by jonadev95** [comment]
@ruffsl youre completely right, that's exactly what should be done. Okay I didn't know that you mean all possible ways to get 'graphics from docker', but as said I think to keep everything safe and seperated we should go with SSH. 

Yes you're right, didn't know that, sorry. Maybe some others should bring in there opinions.
