### ISSUE TITLE
Can't close window with 'exit' or 'ctrl-d'

### ISSUE THREAD

**Issue by raboof** [shockone/black-screen#158]
'exit' gives 'command not found', ctrl-d just doesn't do anything.

**Comment by tcyrus** [comment]
```
$ exit
Black Screen: command "exit" not found.
```

**Comment by iiegor** [comment]
This, probably, can be easily fixed by implementing a new built-in for the 'exit' command.

**Comment by shockone** [comment]
Fixed.
