### ISSUE TITLE
Allow to install using brew

### ISSUE THREAD

**Issue by shockone** [shockone/black-screen#175]

**Comment by G07cha** [comment]
As I know, first of all you need to release at least one version of application. Also I would like to ask, which goal are you want to achieve by providing "brew formula"? It will be one of way to install "black-screen" or additional CLI tool?

**Comment by shockone** [comment]
I think a brew cask should be the only way to install the application because it supports updates.

**Comment by G07cha** [comment]
@shockone what about self-updater? It's more user-friendly.

**Comment by shockone** [comment]
I don't think it is. There are certain benefits in having a single place to update your applications:

* You don't need to think of each one separately 
* It doesn't ask you to update when you start the application with the intent to work and not to think about its new releases. I always have this experience with Firefox: I start it now and then to try something, and every time it asks me to update itself.

**Comment by G07cha** [comment]
>  I start it now and then to try something, and every time it asks me to update itself.
This function can be disabled btw. We don't need to do same as in Firefox, it can be just tiny button with text "Update available" that don't prevent using application at all or it can be just a background update.

**Comment by iiegor** [comment]
// @alebcay

**Comment by shockone** [comment]
Actually, since it's a terminal, it can update itself using brew, you know. :)

**Comment by alebcay** [comment]
Since it's an application bundle, I would encourage you to place it in Homebrew Cask, not homebrew, which is more geared for CLI stuff.

Homebrew Cask currently doesn't support automatic updates. Any update functionality must be handled by the application itself (for now, at least).

**Comment by Nnubes256** [comment]
Here's a working Cask template for 0.0.2:
```ruby
cask 'black-screen' do
  version '0.0.2'
  sha256 'cbab7632af02ad276508e527118f161e9d76db01fe25a2114825b7a28f850a32'

  url "https://github.com/shockone/black-screen/releases/download/v#{version}/Black.Screen.zip"
  appcast "https://github.com/shockone/black-screen/releases.atom",
          checkpoint: 'd646b4da0c86a3c3a9471a75e8ae4a6e11f0bc5c084adcc5de9bdf0c8279cf39'
  name 'Black Screen'
  homepage 'https://github.com/shockone/black-screen'
  license :mit

  app 'Black Screen.app'
end
```

**Comment by shockone** [comment]
`brew cask install black-screen`.
