### ISSUE TITLE
linux/windows port question

### ISSUE THREAD

**Issue by gbaumgart** [shockone/black-screen#182]
hi, 
this looks very promising! You have some pointers for me to do a windows/linux port ? I mean, what's the actual problem to do it? 

thanks,
can't wait!

**Comment by gbaumgart** [comment]
anyone ? if not close it please. 
thanks.

**Comment by j-allard** [comment]
It's an electron app, so it should already be compatible with Linux.

**Comment by shockone** [comment]
The single motivation to keep only an OS X version during development is reduced support time. After `1.0.0` release we'll support all the major platforms.
