### ISSUE TITLE
Context specific auto-completion

### ISSUE THREAD

**Issue by j-allard** [shockone/black-screen#190]
Suggestions are still popping up right after the input has been completed.

Example of current behaviour:
1) Type `to`
2) Select `top` with the arrow key
3) Press _tab_ to auto-complete

Then you can see the `suggestionComponent` automatically popup:
![](http://i.imgur.com/fmmqLOH.png)

I think this behaviour is rather *confusing* (where are these suggestions coming from? why the suggestions seems to be files? `top` has nothing to do with files) and *non-standard*. 

If we look at how others are doing auto-completion (Slack, Twitter, Facebook), the well-established standard seems to be to close the suggestions box after some completion has been performed.

**Comment by shockone** [comment]
Hello, @j-allard. You are right in that there shouldn't be file suggestions for `top`. However, I can't agree that we should hide suggestions right after a completion. Imagine I type `git chec` and complete it as `git checkout`. Obviously, the next thing I want to type is a branch name (well, it could be a file name or something, but you see my point). Now, if we close the autocomplete, I wouldn't know what branches exist before typing at least one letter, which in my opinion is not smart.

The way I plan to handle it is to have definitions for every command, like the following:

```
COMMAND
    : 'git' GIT_OPTION EOF
    : 'top' [TOP_OPTION] EOF
    : 'cd' FILE_NAME EOF

TOP_OPTION
    : '-a'
    | '-F'
    | '-h'
```

This way we won't suggest anything stupid without losing the ability to suggest something smart.

**Comment by shockone** [comment]
Let's discuss it, though.

**Comment by j-allard** [comment]
Yes I see your point and I agree that this would be a nice feature to have. 

Perhaps my PR was a bit too short-minded, but the idea behind it was that if there are currently no heuristics in place to determine what *type* of lexeme should be suggested (other than files, commands or aliases) we might as well just clear it until the suggestions/autocomplete components are able to suggest smarter choices (because right now its somewhat confusing and it feels buggy).

From the definition you showed, I'm guessing you're planning on using a grammar parser? 
http://pegjs.org/ looks nice.

**Comment by shockone** [comment]
Fixed. Now you can use [AutocompletionProvider.forCommand](https://github.com/shockone/black-screen/blob/master/src/Interfaces.ts#L18-L18) to specify the target. In particular, `top` suggestions look like this:
![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/-z6q24-_.png)
