### ISSUE TITLE
i think black-screen is missing paste and find menus and so on like this normal terminal

### ISSUE THREAD

**Issue by joostshao** [shockone/black-screen#194]
i think black-screen is missing paste and find menus and so on like this normal terminal.
ctrl c; ctrl v; and ctrl -f.

**Comment by shockone** [comment]
Hey, @joostshao. There is a paste menu on OS X: ![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/xc8ulspq.png)

Judging from the shortcuts, though, you use some different OS. Sorry, but only OS X is supported at them moment. But if you decide to fix it (you'll need to modify https://github.com/shockone/black-screen/blob/master/src/main/Menu.ts), I'll try to merge the PR as soon as possible.
