### ISSUE TITLE
Split screen

### ISSUE THREAD

**Issue by YaManicKill** [shockone/black-screen#211]
This is a pretty cool project, just thought I'd throw a feature request out there (that I can't see mentioned anywhere else): split screen.

Yes, yes, I know we can all use tmux/screen for that, but split screen built into terminal is perfect as it allows you to change the terminal you are using by clicking on it (rather than having to use a keyboard shortcut) and much easier to resize them, etc.

I would absolutely love if you guys supported this :-)

**Comment by shockone** [comment]
Hey, @YaManicKill. The good news are that horizontal screen is already implemented (`cmd+_`). However, it doesn't work very well yet. In particular, panes aren't resizable and there is no vertical split.

**Comment by shockone** [comment]
A relative issue: https://github.com/shockone/black-screen/issues/198

**Comment by YaManicKill** [comment]
Oh, sorry about that. I didn't see anything in the documentation about split screen, and I clearly didn't search well enough. That's brilliant. Are there plans for vertical split?

**Comment by shockone** [comment]
Yes, eventually it will be implemented because I use it on a daily basis in iTerm2.

**Comment by YaManicKill** [comment]
Brilliant, thanks. I'm really excited about this project :-) looking forward to full linux/windows support as well. I'll finally have a cross-platform terminal emulator. Thanks for all your heard work.
