### ISSUE TITLE
`more` shows text after first screenful as solid blocks

### ISSUE THREAD

**Issue by marnen** [shockone/black-screen#234]
# Environment

Black Screen 0.36.7, Mac OS X 10.11.3

# Steps to reproduce

Use `more` to paginate a file that's more than one screen long

# Expected result

The entire contents of the file are displayed

# Actual result

After the first screenful, all the characters become solid blocks: 
![image](https://cloud.githubusercontent.com/assets/34378/12892756/9a14c282-ce5b-11e5-8b58-915f3cf35535.png)

**Comment by shockone** [comment]
Fixed.
