### ISSUE TITLE
Cursor keys don't work in Emacs

### ISSUE THREAD

**Issue by marnen** [shockone/black-screen#236]
In Black Screen 0.36.7, the cursor keys don't work in Emacs: instead, `up` types `&`, `down` types `(`, `left` types `%`, and `right` types `'`. In iTerm on the same machine, however, Emacs cursor keys work as expected. What would have to happen for this to work in Black Screen?

**Comment by shockone** [comment]
Fixed. Thank you for the report, @marnen.

**Comment by marnen** [comment]
Confirmed, although the cursor doesn't always display properly. Thanks for the quick fix!

**Comment by shockone** [comment]
@marnen, yeah, it's a recently introduced regression with the caret. I'll try to fix it tomorrow and will let you know.

**Comment by shockone** [comment]
@marnen, now the caret should be displayed correctly. You should also remember that Black Screen is currently highly unstable, don't rely on it in your everyday work.

**Comment by marnen** [comment]
@shockone Again, thanks! I know it's somewhat unstable, but I want to play around, see how far I can get with it, and perhaps contribute to it.
