### ISSUE TITLE
`cd -` doesn't work

### ISSUE THREAD

**Issue by marnen** [shockone/black-screen#237]
Black Screen 0.36.7 doesn't understand `cd -` -- that is, it attempts to treat `-` as a directory name.

**Comment by shockone** [comment]
Fixed. Even more: it suggests what the expansion will look like. And proactively tells you there is no previous directory.

![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/3xd6xsfj.png)
![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/fbrf_9bj.png)

**Comment by shockone** [comment]
By the way, 0.36.7 is the version of Electron. We don't have versioning at the moment.

**Comment by marnen** [comment]
@shockone Oh, whoops! I guess I'll refer to versions by Git commit in future.
