### ISSUE TITLE
Implement argument suggestion in autocomplete providers

### ISSUE THREAD

**Issue by mkenne11** [shockone/black-screen#240]
The command option suggestions work well and are straightforward to implement in autocomplete providers. 

An example of this is when I type "git commit" I see options suggested "message=<msg>" and "--cleanup=<mode>".

For some commands however there will be options and arguments. An example is "git checkout" with argument "<branch>". Is it possible to display arguments in autocomplete module suggestions?

It looks like the Git autocomplete plugin is attempting to do this for "git checkout" and "git merge", however no arguments are shown in the autocomplete suggestions (for me on Ubuntu 14.04 anyways).

See https://github.com/shockone/black-screen/blob/master/src/plugins/autocompletion_providers/Git.ts#l129

**Comment by shockone** [comment]
Hi, @mkenne11. Here's what I see when I type `git checkout `. Do I understand you correctly that for the same input you see no suggestions? ![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/7aj4tmii.png)

**Comment by mkenne11** [comment]
Your understanding of my question was correct :) ... My testing of the functionality was wrong :(

I tested "git checkout" in a directory which wasn't a git repository so it didn't show any branches as autocomplete suggestions.

I tested "git checkout" again then in my local blackscreen repo and it worked correctly :)
