### ISSUE TITLE
Error during npm install

### ISSUE THREAD

**Issue by haoyangnz** [shockone/black-screen#241]
`> black-screen@0.0.1 preinstall /Users/haoyangfeng/mos/work/black-screen/black-screen
> npm prune

> black-screen@0.0.1 postinstall /Users/haoyangfeng/mos/work/black-screen/black-screen
> bower prune; bower install; electron-rebuild

Couldn't find electron-prebuilt and no --node-module-version parameter set, always rebuilding

> ptyw.js@0.3.2 install /Users/haoyangfeng/mos/work/black-screen/black-screen/node_modules/ptyw.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node

> nslog@3.0.0 install /Users/haoyangfeng/mos/work/black-screen/black-screen/node_modules/electron-rebuild/node_modules/nslog
> node-gyp rebuild

  CXX(target) Release/obj.target/nslog/src/main.o
  CXX(target) Release/obj.target/nslog/src/nslog_mac.o
  SOLINK_MODULE(target) Release/nslog.node

> fsevents@1.0.0 install /Users/haoyangfeng/mos/work/black-screen/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

Unsupported target version: 0.33.0

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.33.0
node-pre-gyp ERR! stack     at get_runtime_abi (/Users/haoyangfeng/mos/work/black-screen/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:140:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/haoyangfeng/mos/work/black-screen/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:249:19)
node-pre-gyp ERR! stack     at install (/Users/haoyangfeng/mos/work/black-screen/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/haoyangfeng/mos/work/black-screen/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/Users/haoyangfeng/mos/work/black-screen/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/haoyangfeng/mos/work/black-screen/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:425:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:432:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:313:12)
node-pre-gyp ERR! System Darwin 15.3.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/5.1.0/bin/node" "/Users/haoyangfeng/mos/work/black-screen/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/haoyangfeng/mos/work/black-screen/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents
node-pre-gyp ERR! node -v v5.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok 

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.1.0/bin/node" "/Users/haoyangfeng/mos/work/black-screen/black-screen/node_modules/electron-rebuild/node_modules/npm/bin/npm-cli.js" "rebuild" "--target=0.33.0" "--arch=x64"
npm ERR! node v5.1.0
npm ERR! npm  v2.14.6
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/haoyangfeng/mos/work/black-screen/black-screen/node_modules/npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (/Users/haoyangfeng/mos/work/black-screen/black-screen/node_modules/electron-rebuild/lib/spawn.js:55:26)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
`

Any idea?

**Comment by shockone** [comment]
Could you try to remove the directory `~/.node-gyp` and then `npm i` again?

**Comment by haoyangnz** [comment]
@shockone Same error

**Comment by shockone** [comment]
Can't reproduce. Maybe you could try to delete the `node_modules` directory, update `node` to 5.6.0 and try `npm i` again?

**Comment by haoyangnz** [comment]
That worked. Thank you.
