### ISSUE TITLE
Unable to cd: 'command "cd::cd" not found'

### ISSUE THREAD

**Issue by ilkka** [shockone/black-screen#242]
Unable to cd to any directory. Fresh built master.

![2016-02-15 at 08 24](https://cloud.githubusercontent.com/assets/1549/13041204/cd18abfa-d3bd-11e5-8c18-991ec9be58ad.png)

Console output:

```
Download the React DevTools for a better development experience: https://fb.me/react-devtools
jquery.caret.min.js:2 'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach).
index.html:1 Uncaught (in promise) Error: ENOENT: no such file or directory, stat '/Users/ilau/.bash_it'
    at Error (native)
index.html:1 Uncaught (in promise) Error: ENOENT: no such file or directory, stat '/Users/ilau/.bash_it'(…)
index.html:1 Uncaught (in promise) Error: ENOENT: no such file or directory, stat '/Users/ilau/.bash_it'(…)
index.html:1 Uncaught (in promise) Error: ENOENT: no such file or directory, stat '/Users/ilau/.bash_it'(…)
```

Errors are just it complaining about a broken symlink. Removing the symlink does not fix the issue.

**Comment by shockone** [comment]
Is `cd` an alias to something?

**Comment by ilkka** [comment]
Sigh, yes it is. I'm using [b4b4r07/enhancd](https://github.com/b4b4r07/enhancd), but somehow didn't think it would alias `cd` to a function with such a weird name (also, strangely enough `alias` in Black Screen` doesn't print that alias). So, my issue *actually* is that while my aliases are loaded, the shell libraries that provide the functions aren't being called.
