### ISSUE TITLE
Auto-complete for "git commit --cleanup=" doesn't provide option values

### ISSUE THREAD

**Issue by mkenne11** [shockone/black-screen#249]
The Git auto-complete provider (Git.ts) appears to provide the 5 possible "cleanup" mode values for the command "git commit --cleanup=" i.e. modes "strip", "whitespace", "verbatim", "scissors" "or default".

See code at https://github.com/shockone/black-screen/blob/master/src/plugins/autocompletion_providers/Git.ts#l206.

When I type "git commit --cleanup=" in a directory with changes ready to commit (staged) to a git repository the 5 "cleanup" mode options aren't suggested in the auto-complete box. Is this expected behavior.

See screenshot attached.

![git commit --cleanup](https://cloud.githubusercontent.com/assets/12181805/13249056/1253ac60-da76-11e5-8044-38e506de68c7.PNG)

**Comment by mkenne11** [comment]
I'm experimenting with updates to the grep auto-complete provider (Grep.ts) and want to add the same functionality for a grep argument which has a fixed set of options.

**Comment by shockone** [comment]
@mkenne11 autocompletion will be heavily rewritten. Please hold on with your changes unless you're willing to rewrite them as well.

**Comment by mkenne11** [comment]
Thanks I'll hold off to the autocomplete rewrite :)

**Comment by shockone** [comment]
Fixed.
