### ISSUE TITLE
Ampersand in input causes trouble

### ISSUE THREAD

**Issue by Potherca** [shockone/black-screen#250]
Input that contains an ampersand character `&`  has incorrect behaviour.
In the screenshot you can see that instead of the expected, other behaviour is present.

**Expected Behaviour**
```
$ echo '&'
&
$ echo '&foo'
foo
```

** Actual Behaviour** 

![screen shot 2016-02-23 at 13 02 27](https://cloud.githubusercontent.com/assets/195757/13251359/088b45b2-da30-11e5-9841-488fc4b2c51d.png)

**Comment by shockone** [comment]
Perhaps, expected output for `echo '&foo'` should be `&foo`, right?

**Comment by Potherca** [comment]
Correct.

**Comment by shockone** [comment]
Fixed.
