### ISSUE TITLE
After exiting VIM, its window remains to show up above new prompt line.

### ISSUE THREAD

**Issue by frenchbread** [shockone/black-screen#252]
How it looks: 
![screen shot 2016-02-25 at 15 42 41](https://cloud.githubusercontent.com/assets/2122679/13321325/10fd8496-dbd7-11e5-936c-3f12044ad7f2.png)

**Comment by curioussavage** [comment]
I was assuming that was a feature myself

**Comment by zacharyfmarion** [comment]
Yeah the screenshot of the last visual process is a feature, although perhaps adding a setting that provided a toggle for the behaviour wouldn't be a bad idea.

**Comment by frenchbread** [comment]
Ah, I see. Didn't expect that kind of feature :) Idea with a settings option sounds good!

**Comment by shockone** [comment]
Options aren't for free: they complicate the codebase and user experience. I'll either remove it if nobody likes that, or will leave it as is. Please let me know your opinion, guys.

**Comment by frenchbread** [comment]
If option is not easy to implement, I vote for keeping it. Got used to it already. 

But I think, @shockone, you gonna add "Preferences" window/tab anyways so +1 option for changing it wont affect user experience much but rather'll improve it.

**Comment by curioussavage** [comment]
I think I like it too. sometimes I close vim or less and my horrible short term memory makes it necessary to open vim again to see what I just did.
