### ISSUE TITLE
Feature Request: Basic shortcuts for usability purpose

### ISSUE THREAD

**Issue by bahdad** [shockone/black-screen#253]
I found that there is only 1 available shortcut - `Command+T` which will open a new tab

It would be very useful to add at least:
- `Command+[/]` to navigate between opened tabs
- `Command+W` to close current tab

**Comment by shockone** [comment]
`⌘+number` navigates between tabs, `⌘+W` does close it.

**Comment by callistino** [comment]
I tested the `Command+W` to close current tab but `Command+[/]` is still not working. I also use a lot `Command+K` to clear the terminal.
