### ISSUE TITLE
BlackscreenLinux

### ISSUE THREAD

**Issue by tridentlead** [shockone/black-screen#254]
I know linux is not yet supported and am not trying to be a nag but I am trying to get this to work on linux. I have never written any node.js code and am trying to work through some error messages. I was wondering if anyone had any ideas about this one.

> black-screen@0.0.1 start /home/tri/Workspaces/black-screen
> gulp

>[23:20:15] Requiring external module babel-register
>[23:20:16] Using gulpfile ~/Workspaces/black-screen/gulpfile.babel.js
>[23:20:16] Starting 'default'...
>[23:20:16] Starting 'watch'...
>[23:20:16] Starting 'clean'...
>[23:20:16] Finished 'clean' after 40 ms
>[23:20:16] Starting 'typescript'...
>[23:20:16] Starting 'sass'...
>[23:20:16] Starting 'copy-html'...
>[23:20:16] Finished 'default' after 175 ms
>[23:20:16] Finished 'copy-html' after 76 ms
>[23:20:20] gulp-notify: [Black Screen Watcher] SCSS has been compiled.
>[23:20:20] Finished 'sass' after 4.01 s
>[23:20:20] gulp-notify: [Black Screen Watcher] TypeScript has been compiled.
>[23:20:20] Finished 'typescript' after 4.38 s
>[23:20:20] Starting 'build'...
>[23:20:20] Finished 'build' after 3.58 μs
>[23:20:20] Finished 'watch' after 4.45 s

> black-screen@0.0.1 electron /home/tri/Workspaces/black-screen
> electron .

>events.js:141
 >     throw er; // Unhandled 'error' event
      ^

>Error: channel closed
>    at process.target.send (internal/child_process.js:509:16)
>    at Socket.fork.on.data (/home/tri/Workspaces/black-screen/compiled/src/PTYInternal.js:29:33)
>    at emitOne (events.js:77:13)
>    at Socket.emit (events.js:169:7)
>    at readableAddChunk (_stream_readable.js:146:16)
>    at Socket.Readable.push (_stream_readable.js:110:10)
>    at Pipe.onread (net.js:523:20),

**Comment by acarl005** [comment]
+1 for this. won't install on Ubuntu 14.04

**Comment by mapaiva** [comment]
I run the build task for linux using electron-packager with no problem
```sh
gulp build && electron-packager . "$npm_package_productName" --overwrite --platform=linux --arch=x64 --version=$npm_package_electronVersion --out='ReleaseLinux' --icon='./icon.png'
```

But the font of the terminal is kind of weird and ugly. Would be nice define a default font or let the user choose this config.

I'm on Ubuntu Gnome 15.10 64bit
node version: 4.3.2

![captura de tela de 2016-03-07 09-30-42](https://cloud.githubusercontent.com/assets/8807694/13569542/5f08a846-e447-11e5-9958-4b0834f23d81.png)

**Comment by shockone** [comment]
@mapaiva, people are going to be able to choose their favourite font for sure, but not right now. Meanwhile, the default fond was changed to [Hack](https://github.com/chrissimpkins/Hack), if you have it installed.

**Comment by mapaiva** [comment]
@shockone got it. Thanks for the reply
