### ISSUE TITLE
Crashes if using a shell other than bash or zsh (e.g. fish)

### ISSUE THREAD

**Issue by despairblue** [shockone/black-screen#265]
```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Object.<anonymous> (/Users/danny/git/black-screen/compiled/src/PTYInternal.js:15:62)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:151:18)
    at node.js:1007:3
```

It would be cool if the error message could be a little more descriptive.

**Comment by MiracleBlue** [comment]
Noticed that in the file PTYInternal.js, it has a config map for bash and zsh to run without their rc files and some other settings.  I added fish as a blank entry and got the UI to work (sort of) but other strange errors appear relating to promise rejection, and without source maps, it's hard to find what's going on.

**Comment by despairblue** [comment]
Yeah, I gave up as well. Just thought that a check if the key exitsts in the map would make sense, so that it outputs something like `Your shell (fish) is not supported yet.` instead of this ominous error message.

**Comment by despairblue** [comment]
BTW, the promise rejection happens because black-screen tries to alias something and fish does not support aliases, so it just prints out `Fish implements aliases using functions. Use 'functions' builtin to see list of functions and 'functions function_name' to see function definition, type 'help alias' for more information.` and returns 1.

**Comment by shockone** [comment]
Now we default to `/bin/bash` if your shell is neither bash nor zsh.
