### ISSUE TITLE
Extraterm: a similar terminal project that is based on Electron and TypeScript

### ISSUE THREAD

**Issue by FunkMonkey** [shockone/black-screen#266]
There is a very similar project called [Extraterm](https://github.com/sedwards2009/extraterm), which also provides a terminal based on Electron and Typescript.

I just wanted to cross-reference both projects. Guess they can inspire each other. 

[edit] ...or even work out a compatible API and share code

**Comment by shockone** [comment]
That's good to know, thank you. I don't know what to do with this issue, so I'll close it, if you don't mind.

**Comment by Ornataweaver** [comment]
Would you open this issue again? Or open it in a discussions part of your project? I think the community around upterm can help extraterm.
Check the discussion I had with them at https://github.com/sedwards2009/extraterm/issues/70#issuecomment-354504881.

**Comment by Ornataweaver** [comment]
You guys can breathe so much more life into extraterm.
