### ISSUE TITLE
(OSX) High CPU usage

### ISSUE THREAD

**Issue by kevin-smets** [shockone/black-screen#275]
The CPU usage on El Capitan is always around 160 / 170%. I thought it was indexing my system or something but after leaving it open for a day, still no improvement.

<img width="815" alt="screen shot 2016-03-22 at 11 12 56" src="https://cloud.githubusercontent.com/assets/4222494/13948398/0d35415c-f020-11e5-80b1-40a3400555b6.png">

Typing a command also goes quite slowly, probably a side effect of the high CPU usage.

**Comment by shockone** [comment]
Does it happen all the time?

![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/xbsks_qt.png)

**Comment by shockone** [comment]
If somebody else has the same issue, please leave a comment.

**Comment by kevin-smets** [comment]
Will update to the latest version and will package again. I'll repost asap.

**Comment by kevin-smets** [comment]
Ok, the latest version does not seem to be impacted anymore. Weird, had this happen on a few versions so I was losing hope :D. Now it is usable again! Thanks for all your hard work.

**Comment by luco** [comment]
@shockone 

It seems to happen to me when I split my view.

![image](https://cloud.githubusercontent.com/assets/246373/17895093/4dcfd184-6922-11e6-8da7-87c80b7a357e.png)

When I close the splits, it becomes normal again.
