### ISSUE TITLE
Error when running black-screen in Ubuntu

### ISSUE THREAD

**Issue by mkenne11** [shockone/black-screen#276]
Since recent changes to the black-screen application, on Ubuntu 15.10 I am getting an an error when attempting to run the application (using "npm start"). See error in Figure 1.
Note. I could run the application successfully prior to these changes.

The error is produced by the command in gulpfile.js https://github.com/shockone/black-screen/blob/master/gulpfile.js#l43.
``` 
gulp.task("typescript", $.shell.task("npm run tsc", {cwd: "/Users/me/dev/black-screen"}));
```
If I change this to the following the application starts correctly:
```
gulp.task("typescript", $.shell.task("npm run tsc"));
```
Do you think this is an issue with just Linux? I am assuming it's working fine on OS X.

Figure 1. black-screen build error
![gulp-build-error](https://cloud.githubusercontent.com/assets/12181805/13984479/8df73ee6-f14a-11e5-94b9-c80beced85b8.PNG)

**Comment by verzil** [comment]
Hey i believe this happens because you don't have typescript compiler installed.  I don't see tsc in the package.json dependencies. You could install it globally with `npm install tsc -g` and see if you are still hitting this error

**Comment by mkenne11** [comment]
Thanks for the feedback @verzil. I tried doing a global install of the the typescript compiler globally (using ```npm install -g tsc```), however I still get the same error when attempting to run the application. I see i ran successfully for you on Arch - so it's probably an issue with my configuration.
Thanks again.

**Comment by sedwards2009** [comment]
`tsc` is in the package dev dependencies. It is 'typescript'. Everyone who does a `npm install` should get it.

**Comment by verzil** [comment]
@sedwards2009 Sorry I thought typescript compiler is a separate package called tsc for some reason...
@mkenne11 
- There are a few things we could try. Re clone the repo, make sure you have the latest. 
- then follow the standard install procedures again.
- if it is still not working, then maybe try manuelly compile it using `tsc filename`, (if you don't have it installed globally, you could do `node_modules/typescript/bin/tsc filename`.)

it could even be.. something with gulp. Because I'm getting permission denyed when running `npm start` sometimes. 

From reading the logs, I assume its because gulp couldn't find tsc :/

**Comment by mehcode** [comment]
The whole problem here is `{cwd: "/Users/me/dev/black-screen"}`. That obviously isn't everybody's working directory. Just remove that or use something a bit smarter like `__dirname` and let's call this fixed.

**Comment by mkenne11** [comment]
Thanks @mehcode  - changing "cwd" to my black-screen working directory (```/home/michael/development/black-screen```) did fix the problem :)

When I first encountered the error I set "cwd" to the relative path of my working directory (```~/development/black-screen```) but encountered the same error. Looks like it needs to be set to the absolute path.

**Comment by shockone** [comment]
I've removed the path. Sorry, guys.

**Comment by mkenne11** [comment]
No problems @shockone.
