### ISSUE TITLE
directory autocomplete doesn't prioritize exact prefix match

### ISSUE THREAD

**Issue by jaredly** [shockone/black-screen#279]
If I have two directories, both of which "fuzzy match" and the second (lexicographically) of which "exact prefix matches", the fuzzy match wins.
I would expect the exact prefix match to win.

e.g.
directories: `django-feedback` and `feast`
typing `fe` + <kbd>tab</kbd> gives me `django-feedback`, not `feast` as I'd expect

**Comment by zozzz** [comment]
I think the [fuzzaldrin-plu](https://www.npmjs.com/package/fuzzaldrin-plus) package is solves the problem.

**Comment by shockone** [comment]
Now that fuzzy match is disabled, the issue doesn't exist anymore.
