### ISSUE TITLE
Automate build?

### ISSUE THREAD

**Issue by jcgertig** [shockone/black-screen#28]
Maybe look into https://github.com/mainyaa/gulp-electron and https://codeship.com so that you can build a executable for all platforms automatically on a successful deploy.

**Comment by shockone** [comment]
That is a great idea. I'll try to do it, but if you're interested in contributing and want to make it happen sooner, you're welcome to go ahead. If you need access to the repository, please let me know and I'll add you.

**Comment by jcgertig** [comment]
Sure I can start

**Comment by jcgertig** [comment]
you can see what Im working on here https://github.com/jcgertig/black-screen/tree/add-auto-build

**Comment by shockone** [comment]
@jcgertig, please open a pull request. I will automatically update with your latest changes in the branch.

**Comment by joshtoo** [comment]
@shockone - I don't think he was quite done. We are splitting tasks as we get to them from #63 some of which are dependent on each others work. His PR will be opened to https://github.com/black-screen/black-screen/tree/63_travis-ci as will all the others from #63

**Comment by shockone** [comment]
@jcgertig are you still working on this?

**Comment by jcgertig** [comment]
Sorry ive been sick. Yeah all I need to add is a tagging and push back to github

**Comment by shockone** [comment]
@jcgertig you have nothing to be sorry about. Hope you feel better now.

**Comment by jcgertig** [comment]
have you been able to fix the 

```
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.
```

that you get when you package?

it happens for prompt.js

**Comment by dantman** [comment]
I've found that `addComponentAsRefTo` often happens in React based code when you have 2 copies of React.
