### ISSUE TITLE
Switching between tabs removes command history

### ISSUE THREAD

**Issue by mkenne11** [shockone/black-screen#280]
If the user switches from one tab (after running commands) to a second tab, then back to the first tab - (in the first tab) the results of commands run are shown however commands run are no longer displayed.

As an example see the screenshots below. In this example the following scenario occured:
- Initially 3 tabs were opened.
- Three commands were run in tab # 3. See Screenshot 1.
- The user switches to tab # 2 then back to tab # 3.
- In tab # 3 the results of the 3 commands are shown however the individual commands are no longer shown. See Screenshot 2.

Screenshot 1.
![session history - before switch](https://cloud.githubusercontent.com/assets/12181805/14410133/41f96de2-ff6a-11e5-8294-d8e8853b7432.PNG)

Screenshot 2.
![session history - after switch](https://cloud.githubusercontent.com/assets/12181805/14410135/46f744ae-ff6a-11e5-87f2-71323278998a.PNG)

**Comment by shockone** [comment]
There is more to read about this bug in the linked pull request.

**Comment by mkenne11** [comment]
Thanks @shockone - yep I saw your comments in the pr. I'll have an attempt at trying to implement the suggested fix hopefully I'll find time. 

BTW. I'm keen to learn typescript and react and this seems like a good project to start with :)
