### ISSUE TITLE
Failing to install on Mac OS X Mavericks with CommandLineTools instead of Xcode

### ISSUE THREAD

**Issue by erwagasore** [shockone/black-screen#31]
```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

**Comment by shockone** [comment]
@erwagasore, please try this solution. http://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error-on-osx-mavericks

**Comment by erwagasore** [comment]
The solution suggest people to install XCode. That is what many people have installed CommandLineTools to avoid

**Comment by shockone** [comment]
Sorry, I misunderstood you at first. Will try to make it build without XCode.

**Comment by erwagasore** [comment]
+1

**Comment by mzgnr** [comment]
I think Electron requires Xcode for building.

**Comment by alebcay** [comment]
Yes, Electron does require Xcode >= 5.1 for building on OS X per the Electron docs.
