### ISSUE TITLE
Use electron-builder

### ISSUE THREAD

**Issue by shockone** [shockone/black-screen#310]
https://github.com/electron-userland/electron-builder

**Comment by DivineDominion** [comment]
It seems that package is very mature, with packaging and server and all!

**Comment by shockone** [comment]
[ ] Release notes

**Comment by shockone** [comment]
Auto-updating the application requires signing the code. A certificate to sign in costs $59. I think we'll be updating it via homebrew instead.

**Comment by DivineDominion** [comment]
Sounds reasonable :)
