### ISSUE TITLE
App freezes after first command

### ISSUE THREAD

**Issue by olegakbarov** [shockone/black-screen#335]
Got my app freezed after (any) first command, any ideas why this might happen? CMD+R doesn't help, as well as relauch and rebuild.

The following actions were taken before: 

1. Clone and install
2. Navigate back and forth to directories
3. Then suddenly everything freezed

Any chance it could be due to number of files in directory? 

PS. The project looks awesome, really impressed!

![black-screen](https://dl.dropboxusercontent.com/u/68648872/bs.png)

**Comment by olegakbarov** [comment]
Well, opening DevTools made it pretty obvious:
```
/Users/oleg/code/black-screen/compiled/src/Session.js:31 Uncaught Error: EMFILE: too many open files, open '/Users/oleg/.black-screen-state'
```

**Comment by lucacri** [comment]
Same issue for me :(

**Comment by thomasbritton** [comment]
Same issue for me, shame as this looks really cool.

**Comment by olegakbarov** [comment]
I 'solved' this by removing the ` '/Users/oleg/.black-screen-state'` file and rebuilding the package
Now navigating the directories with caution.

**Comment by shockone** [comment]
Fixed.
