### ISSUE TITLE
Alias and Synopsis for updated autocomplete functionality

### ISSUE THREAD

**Issue by mkenne11** [shockone/black-screen#344]
I see you are updating the auto-complete function and noticed that the "withAlias" and "withSynopsis" properties haven't been implemented for options. An example is in the updated Git auto-complete provider:
https://github.com/shockone/black-screen/blob/master/src/plugins/autocompletion_providers/Git.ts

Am curious - do you plan to implement these in the updated auto-complete functionality?

I am writing some auto-complete providers myself and will hold off it you plan to add these properties.

**Comment by shockone** [comment]
You can create `withDesciption` by copying this line and replacing corresponding parts. https://github.com/shockone/black-screen/blob/master/src/plugins/autocompletion_providers/Suggestions.ts#L163-L163

As for `withAlias`, it can be easily composed using the `choice` parser. If you need more details I can write an example, but that should be simple.

**Comment by mkenne11** [comment]
Thanks @shockone.
