### ISSUE TITLE
Auto-updater

### ISSUE THREAD

**Issue by DivineDominion** [shockone/black-screen#347]
I'd like to help on this but want to make this open for discussions first. Targeting OS X, shipping an app bundle with Sparkle updating would be easy. But cross-platform is another beast.

Maybe fombining this with Travis-CI could work: build the binaries in a worker, then upload to AWS or a gh-pages branch for hosting the zipped files.

**Comment by shockone** [comment]
I'd appreciate your help, @DivineDominion. Could you please go into more details on how you plan do to that? I planned to use this one https://github.com/shockone/black-screen/issues/310, but I don't have a strong opinion.

**Comment by DivineDominion** [comment]
Cool, if such a thing already exists, I guess that's a better way to go! Didn't see the issue when I was scanning for "update" :)
