### ISSUE TITLE
Quake-style dropdown feature

### ISSUE THREAD

**Issue by varemenos** [shockone/black-screen#35]
I understand this is not a feature that's implemented easily but please consider adding quake-style dropdown support in the future.

**Comment by G07cha** [comment]
![quake-style dropdown example](http://klickverbot.at/blog/2011/02/quake-style-terminal-on-osx/quake4-console.png)

**Comment by rileyjshaw** [comment]
Wasn't quite sure what this meant, so I checked [Wikipedia](https://en.wikipedia.org/wiki/Console_(video_game_CLI)):

 > A classic console is a box that scrolls down from the top of the screen, and is found in most computer games. This style was made popular with Quake (1996). There are other forms of console:

**Comment by G07cha** [comment]
For now iTerm2 support dropdown functionality(I'm using it by myself) ![fdsf](https://plausiblethought.net/assets/images/posts/iterm2.png) 
is it feature that you want to see? If yes, why you don't using iTerm2?

**Comment by shockone** [comment]
We depend on Electron, which currently has no ability to render such windows. I'll reopen the issue if it appears. https://github.com/atom/electron/blob/master/docs/api/browser-window.md

**Comment by Odol** [comment]
It is entirely easy and possible make quake style console whit electron 
simply you must listen and inherit  the keyboard events from main OS process, from the electron main process, after u must calculate the desktop height, 
and send the window outside the visible range :racing_car:    

```javascript

const { screen } = electron; 
const { height, } = screen.getPrimaryDisplay().workAreaSize;

 window.setAlwaysOnTop(true);
 window.setPosition(0, ~height, true);
```

if you want you can create an attractive animation here;
note: electronjs support backgrounds whit opacity :)
