### ISSUE TITLE
Non-US keyboards aren't correctly mapped

### ISSUE THREAD

**Issue by RuiCarneiro** [shockone/black-screen#351]
Tested with PT-PT keyboard.

**Comment by Gandem** [comment]
Tested with french keyboard on Mac OS X, same issue.

**Comment by RuiCarneiro** [comment]
Works right now

**Comment by Gandem** [comment]
Non US-keyboards are still incorrectly mapped inside vim. I get a sort of hybrid keyboard with all letters correctly mapped, but symbols and numbers not.

**Comment by helton** [comment]
I've the same issue with a PT-BR keyboard layout.

**Comment by Gandem** [comment]
I got the main culprit, this function seems to remap keys only for US keyboards.

https://github.com/shockone/black-screen/blob/master/src/utils/Common.ts#L222-339

**Comment by jiserra** [comment]
Same issue with ES-ES keyboard

**Comment by shockone** [comment]
Could you please verify it works in v0.0.42?

**Comment by jiserra** [comment]
Yes, it's working fine on v0.0.42!
