### ISSUE TITLE
Command Error - Now can't type

### ISSUE THREAD

**Issue by alexbowers** [shockone/black-screen#352]
![image](https://cloud.githubusercontent.com/assets/842974/15453878/0a904360-201e-11e6-8a7e-89297f52b8d8.png)

**Comment by alexbowers** [comment]
For me it seems any command in this folder is failing. 
![image](https://cloud.githubusercontent.com/assets/842974/15453885/3ced8e1c-201e-11e6-8257-c4c35e991430.png)

![image](https://cloud.githubusercontent.com/assets/842974/15453886/4501ec1a-201e-11e6-8353-d50701793391.png)

![image](https://cloud.githubusercontent.com/assets/842974/15453887/4b3f5a2c-201e-11e6-9c59-c42d2d6787e9.png)

**Comment by alexbowers** [comment]
![image](https://cloud.githubusercontent.com/assets/842974/15453890/66815402-201e-11e6-9a49-a5c087512e5f.png)

**Comment by vahnag** [comment]
I have the same problem. None of the commands work.

**Comment by sinstein** [comment]
The developer console in the app appears like 
<img width="1680" alt="Console Error Log" src="https://cloud.githubusercontent.com/assets/4283218/15460323/48fb68b4-20cd-11e6-9a50-f2854e4f1033.png">

**Comment by GijsGoudzwaard** [comment]
+1

**Comment by tanaydin** [comment]
<img width="1440" alt="screen shot 2016-05-23 at 13 43 24" src="https://cloud.githubusercontent.com/assets/400388/15468324/59447a84-20ec-11e6-8740-67d8372fb975.png">

**Comment by aurelien-ldp** [comment]
Same problem here, I think it'll be great to use [graceful-fs](https://github.com/isaacs/node-graceful-fs).

Error explanation here: [node and Error: EMFILE, too many open files](http://stackoverflow.com/questions/8965606/node-and-error-emfile-too-many-open-files)

Has anybody considered using graceful-fs as it may fix the issue ? @shockone ?

**Comment by nickb1080** [comment]
It seems like it's trying to watch all files when the working directory is a git repository. Is that accurate?

**Comment by allistera** [comment]
Also getting this issue when doing ls/cd where the current working directory is a relatively small git project, error is:

`Uncaught (in promise) Error: EMFILE: too many open files, scandir '/Users/allisterantosik/Sites/control-ui/'
    at Error (native)`

Cant cd to any other directory due to this.

**Comment by shockone** [comment]
Fixed.
