### ISSUE TITLE
[bug] [cosmetic] white bar at bottom of window

### ISSUE THREAD

**Issue by sg-s** [shockone/black-screen#353]
There's a white bar in the bottom of the window, which shouldn't be there:

![screen shot 2016-05-22 at 09 40 24](https://cloud.githubusercontent.com/assets/6005346/15454257/6bc8f36a-2001-11e6-82b8-33504abbae3c.png)

running on Mac OS X 10.11.5
Electron 1.1.0
Node v.6.2.0

**Comment by shockone** [comment]
Could you please try again, @sg-s?

**Comment by sg-s** [comment]
Hi @shockone 

sorry, this didn't fix it for me. I get the same behaviour. 

While installing/updating black-screen, I got the following warnings:

```
npm WARN lifecycle black-screen@0.0.1~preinstall: cannot run in wd %s %s (wd=%s) black-screen@0.0.1 npm prune /code/black-screen
npm WARN lifecycle black-screen@0.0.1~postinstall: cannot run in wd %s %s (wd=%s) black-screen@0.0.1 npm run recompile /code/black-screen
npm WARN tslint@3.10.2 requires a peer of typescript@>=1.7.3 but none was installed.
```

**Comment by shockone** [comment]
Would you be able to check in development tools what causes the issue?

**Comment by sg-s** [comment]
sure thing -- can you be more specific as to what and where I should look for? thanks.

**Comment by ignaciopicun** [comment]
HI guys! It's a css overflow-x: scroll property the one that is causing this issue, changing it to auto fix the problems.

<img width="966" alt="screen shot 2016-07-19 at 1 59 13 pm" src="https://cloud.githubusercontent.com/assets/6604687/16958987/4d1a42ee-4db9-11e6-9b5d-f9e201668d67.png">

**Comment by shockone** [comment]
You must be using an older version. The latest one doesn't have `overflow-x` at all. https://github.com/shockone/black-screen/releases

**Comment by sg-s** [comment]
wow! this fixed the problem, but created two new ones:

1) now there's a white bar on the right
2) now, i can't move the window anywhere. It's pinned in place, and I can't drag it anywhere. ???

![screen shot 2016-07-20 at 08 57 01](https://cloud.githubusercontent.com/assets/6005346/16987024/eeba6450-4e57-11e6-905c-55c60bcaf590.png)

**Comment by shockone** [comment]
I've created separate issues for those. 
https://github.com/shockone/black-screen/issues/626
https://github.com/shockone/black-screen/issues/627

**Comment by shockone** [comment]
@sg-s, fixed both in v.0.2.7

**Comment by sg-s** [comment]
thanks so much, it's awesome!
