### ISSUE TITLE
Missing LANG Environment Variable

### ISSUE THREAD

**Issue by kevinastone** [shockone/black-screen#356]
Expected `LANG=en_US.UTF-8` on my OS X machine.  This causes error reading my `.vimrc` since it specifies listchars in utf-8:

```
Error detected while processing $HOME/.vimrc:
line   60:
E474: Invalid argument: listchars=tab:»·,trail:·,eol:¬
Press ENTER or type command to continue 
```

**Comment by shockone** [comment]
Works for me. Can you try again with the latest master?

**Comment by kevinastone** [comment]
Yep, fixed in master.
