### ISSUE TITLE
Evaluate ENV variables

### ISSUE THREAD

**Issue by Kerumen** [shockone/black-screen#357]
Evaluating ENV variables doesn't work:

In zsh:
```
$ echo $TMPDIR
/var/folders/mf/l76gnc2s5yl6tst6xx7b7n7w0000gp/T/
```

in Black Screen:
```
$ echo $TMPDIR
$TMPDIR
```

It would be awesome to add this (and even more awesome with autocomplete)!

**Comment by nfischer** [comment]
+1 to autocomplete

**Comment by shockone** [comment]
The evaluating part is fixed. I'll create a separate card for autocomplete.

**Comment by shockone** [comment]
Implemented.
