### ISSUE TITLE
Is it possible to `grep`?

### ISSUE THREAD

**Issue by borNfreee** [shockone/black-screen#358]
`ls -la | grep test`

Output is:

```
ls: git: No such file or directory
ls: grep: No such file or directory
ls: |: No such file or directory
```

**Comment by vprigent** [comment]
It seems that we can't use the pipe `|`
Didn't work for me as well for a `ls -a | tail -3`

**Comment by shockone** [comment]
Thank you for reporting this, @borNfreee. I think I know where I introduced this bug. Will let you know when it's fixed, guys.

**Comment by shockone** [comment]
Should work now, @borNfreee.

**Comment by borNfreee** [comment]
thank you

**Comment by dsandstrom** [comment]
`alias | grep git` returns all aliases, not just the ones that include the text "git".

I'm using macOS, zsh, v0.4.0 from homebrew.
