### ISSUE TITLE
No Cursor and hangs after closing vim

### ISSUE THREAD

**Issue by jtanmay** [shockone/black-screen#359]
The product looks great. Trying for first time, i tried to work with vim. The vim works great, except when I close it, the screen gets frozen! and i have to quit the program.

Let me know if you need more info!

**Comment by shockone** [comment]
Does it still happen with the latest master?

**Comment by jtanmay-dev** [comment]
Seems the latest is even failing to run for me!! :(

Below is the output.



npm WARN engineStrict Per-package engineStrict (found in this package's package.json)
npm WARN engineStrict won't be used in npm 3+. Use the config setting `engine-strict` instead.
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package typescript@1.9.0-dev.20160525-1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer tslint@3.10.2 wants typescript@>=1.7.3

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tjoshi/black-screen/npm-debug.log

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 prestart: `npm install && npm run compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the black-screen@0.0.1 prestart script 'npm install && npm run compile'.
npm ERR! This is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && npm run compile
npm ERR! You can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tjoshi/black-screen/npm-debug.log
➜  black-screen git:(master)

**Comment by Gandem** [comment]
Updating node to latest v6.2.0 seems to fix the problem
