### ISSUE TITLE
Autocompletion menu offscreen

### ISSUE THREAD

**Issue by fabiocaccamo** [shockone/black-screen#361]
![schermata 2016-05-23 alle 11 00 32](https://cloud.githubusercontent.com/assets/1035294/15465599/a99f92e6-20d5-11e6-9f6e-c4e5799a3672.png)

**Comment by shockone** [comment]
You mean it overlaps with the prompt line, right? That's by design; I think it looks better this way.

**Comment by ekaragodin** [comment]
Maybe move the menu up when the bottom of the space is not enough?
![image](https://cloud.githubusercontent.com/assets/72644/15474909/e60c767e-2128-11e6-893f-224cfc29f0a5.png)

**Comment by ekaragodin** [comment]
Maybe move the menu up when the bottom of the space is not enough?
![image](https://cloud.githubusercontent.com/assets/72644/15474909/e60c767e-2128-11e6-893f-224cfc29f0a5.png)

**Comment by shockone** [comment]
I'm sorry, it's not true. My memory betray me: by design it shouldn't have overlapped. Reopening.
