### ISSUE TITLE
Application opens maximized, unresizeable

### ISSUE THREAD

**Issue by jbcpollak** [shockone/black-screen#366]
Is it by design that the app opens maximized and unresizeable? I can go into full screen mode, but I cannot shrink the window smaller or move it around the screen.

**Comment by DanielRamosAcosta** [comment]
Same here... 😭

**Comment by shockone** [comment]
The window should remember its size, but it's not implemented yet. Moving and resizing should be fixed now.

**Comment by jbcpollak** [comment]
confirmed - I can resize and move window now
