### ISSUE TITLE
Not working with zsh default shell in mac os el capitan. Screen with errors.

### ISSUE THREAD

**Issue by idchlife** [shockone/black-screen#373]
![image](https://cloud.githubusercontent.com/assets/4563032/15500347/f15a393e-21b0-11e6-887e-f57aeb062bd5.png)

**Comment by lazywithclass** [comment]
See if this also applies to you https://github.com/shockone/black-screen/issues/364#issuecomment-221311463

**Comment by shockone** [comment]
Fixed.
