### ISSUE TITLE
Crashes whenever working directory has a dot (".") in its name

### ISSUE THREAD

**Issue by charleshaa** [shockone/black-screen#375]
When working in a directory with a dot in its name, every command fails, no new line is appended and I am forced to close the application. Even `cd ..` will crash so I had to navigate back to `~/` by right-clicking the dock icon.

It does this only when the actual working directory has a dot, not if cd into a subfolder...

Will crash in : `~/my.folder`
Will not crash in: `~/my.folder/subfolder`

**Comment by shockone** [comment]
Works fine for me. Could you check again with the latest master?
![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/sugzv7fn.png)
