### ISSUE TITLE
Install fails in OSX

### ISSUE THREAD

**Issue by juanaraya** [shockone/black-screen#376]
Hi, i trying to install the last version in OSX but it fails with this error:

`Tesla:black-screen juan$ npm i

> black-screen@0.0.1 preinstall /Users/juan/black-screen
> npm prune

|
> pty.js@0.3.0 install /Users/juan/black-screen/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node

> black-screen@0.0.1 postinstall /Users/juan/black-screen
> npm run recompile

> black-screen@0.0.1 recompile /Users/juan/black-screen
> export ELECTRON_VERSION=$(npm run electron-version --silent); HOME=~/.electron-gyp cd node_modules/pty.js; node-gyp rebuild --target=$ELECTRON_VERSION --arch=x64 --dist-url=https://atom.io/download/atom-shell

  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node
npm WARN engineStrict Per-package engineStrict (found in this package's package.json)
npm WARN engineStrict won't be used in npm 3+. Use the config setting `engine-strict` instead.
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package typescript@1.9.0-dev.20160514 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer tslint@3.10.2 wants typescript@>=1.7.3

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/juan/black-screen/npm-debug.log`

It is probably that the problem was my environment and not the release but i doesn't have experience with npm and related stuff so any help would be appreciated.

Thanks.

**Comment by nbarbettini** [comment]
Same issue for me.

**Comment by TimBuckley** [comment]
No problems here

**Comment by bzztbomb** [comment]
I'm getting the same error, node 4.4.4 and npm 2.15.1

**Comment by amwmedia** [comment]
I was having a similar problem and updating npm (`npm update -g npm`) seems to have fixed it for me

**Comment by bzztbomb** [comment]
Weird, I updated npm and re-ran install.  Worked for me. 4.4.4, npm 3.9.2. Thanks @amwmedia

**Comment by shockone** [comment]
Removing the `node_modules` subfolder and doing `npm install` again should help.
