### ISSUE TITLE
Ubuntu 16.04 UNMET PEER DEPENDENCY typescript@1.9.0-dev.20160514

### ISSUE THREAD

**Issue by 4p** [shockone/black-screen#387]
Hello.
I got only this error installing on Ubuntu.
UNMET PEER DEPENDENCY typescript@1.9.0-dev.20160514

So. On npm start my CPU become a lil insane. 
iowait turn arround 50% for 5 minutes.
Now all is ok.

Dev tool console reply only this.
/home/o/Documents/tools/black-screen/node_modules/react/lib/ReactDOM.js:75 Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools

When htop is launched I cannot click on content. 
F1  to F10 have the same issue don't work.

I'll give a reply when i'll get some time for try to build it on Linux.

**Comment by silentwarrior** [comment]
`➜  black-screen git:(master) npm i                                                                    

> black-screen@0.0.1 preinstall /home/joaoc/Projects/misc/black-screen
> npm prune

/
> pty.js@0.3.0 install /home/joaoc/Projects/misc/black-screen/node_modules/pty.js
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/joaoc/Projects/misc/black-screen/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyFork(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/unix/pty.cc:222:34: warning: ignoring return value of ‘int chdir(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
       if (strlen(cwd)) chdir(cwd);
                                  ^
  SOLINK_MODULE(target) Release/obj.target/pty.node
  COPY Release/pty.node
make: Leaving directory `/home/joaoc/Projects/misc/black-screen/node_modules/pty.js/build'

> black-screen@0.0.1 postinstall /home/joaoc/Projects/misc/black-screen
> npm run recompile


> black-screen@0.0.1 recompile /home/joaoc/Projects/misc/black-screen
> export ELECTRON_VERSION=$(npm run electron-version --silent); HOME=~/.electron-gyp cd node_modules/pty.js; node-gyp rebuild --target=$ELECTRON_VERSION --arch=x64 --dist-url=https://atom.io/download/atom-shell

make: Entering directory `/home/joaoc/Projects/misc/black-screen/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyFork(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/unix/pty.cc:222:34: warning: ignoring return value of ‘int chdir(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
       if (strlen(cwd)) chdir(cwd);
                                  ^
  SOLINK_MODULE(target) Release/obj.target/pty.node
  COPY Release/pty.node
make: Leaving directory `/home/joaoc/Projects/misc/black-screen/node_modules/pty.js/build'
npm WARN engineStrict Per-package engineStrict (found in this package's package.json) 
npm WARN engineStrict won't be used in npm 3+. Use the config setting `engine-strict` instead.
npm ERR! Linux 4.2.0-30-generic
npm ERR! argv "/home/joaoc/.nvm/versions/node/v4.4.1/bin/node" "/home/joaoc/.nvm/versions/node/v4.4.1/bin/npm" "i"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package typescript@1.9.0-dev.20160514 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer tslint@3.10.2 wants typescript@>=1.7.3

npm ERR! Please include the following file with any support request:
npm ERR!     /home/joaoc/Projects/misc/black-screen/npm-debug.log
➜  black-screen git:(master) 
`

**Comment by 4p** [comment]
@silentwarrior try to use nvm

➜  ~ nvm --version                                                      [2.3.0]
0.31.0
➜  ~ npm --version                                                      [2.3.0]
3.8.8
➜  ~ node --version                                                     [2.3.0]
v4.4.3
➜  ~

**Comment by 4p** [comment]
➜  black-screen git:(master) npm start                                                        [2.3.0]

> black-screen@0.0.1 start /home/o/Documents/tools/black-screen
> npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron


> black-screen@0.0.1 compile /home/o/Documents/tools/black-screen
> npm run cleanup && npm run compile-tsc && npm run compile-scss && npm run copy-html


> black-screen@0.0.1 cleanup /home/o/Documents/tools/black-screen
> rm -rf compiled


> black-screen@0.0.1 compile-tsc /home/o/Documents/tools/black-screen
> tsc


> black-screen@0.0.1 compile-scss /home/o/Documents/tools/black-screen
> node-sass stylesheets/main.scss compiled/all.css > /dev/tty

Rendering Complete, saving .css file...
Wrote CSS to /home/o/Documents/tools/black-screen/compiled/all.css

> black-screen@0.0.1 copy-html /home/o/Documents/tools/black-screen
> cp src/views/index.html compiled/src/views > /dev/tty


> black-screen@0.0.1 electron /home/o/Documents/tools/black-screen
> electron .

6:57:49 PM - Compilation complete. Watching for file changes.

**Comment by shockone** [comment]
Removing the `node_modules` directory and then `npm install` should help. It's some caching issue.
