### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by Emeraude** [shockone/black-screen#394]
On installation I get those two deprecation warnings. Please note that **jade** module could be removed from npm registry anytime (There is no warranty it's still available since may 12, according to this [issue](https://github.com/pugjs/pug/issues/2184)).

```
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
```

I'm using an up-to-date archlinux, node 6.2.0 and npm 3.9.2

**Comment by shockone** [comment]
Those are transient dependencies, and we really have no influence on them. Besides, it hardly matters.
