### ISSUE TITLE
Not all readline bindings work

### ISSUE THREAD

**Issue by zcdunn** [shockone/black-screen#398]
alt-b inserts ∫ instead of moving left one word
alt-f inserts f instead of moving right one word
ctrl-d quits the app instead of deleting the character underneath the cursor
ctrl-u doesn't do anything; should delete from cursor to end of line
alt-d inserts ∂ instead of deleting until next word

These are the ones I've noticed missing, though there could be more. There is no output in the dev console when these bindings are used.

**Comment by shockone** [comment]
Please use the binding for regular input fields. ⌥+arrow, delete, cmd+delete, etc.
