### ISSUE TITLE
ported to an Atom built in plugin?

### ISSUE THREAD

**Issue by jake-g** [shockone/black-screen#40]
this would be useful i'd imagine. also feed off the same theme engine

**Comment by bucaran** [comment]
Yes!. This is what would make the most sense to me at least :smile:

**Comment by shockone** [comment]
@jake-g I'm afraid it's not going to happen for the following reasons:

* We plan to have our own plugins, and it would be a mess to locate them among Atom packages.
* It's not very convenient for users to install a text editor to have a terminal.
* Fitting into the Atom's architecture is harder than to build it from scratch. I tried.

**Comment by G07cha** [comment]
Also Atom already have [terminal package](https://atom.io/packages/atom-terminal-panel)

**Comment by abhi18av** [comment]
Hi guys! Hey, maybe we can make something like atomic-chrome plugin for Atom which just redirects the desired command to BlackScreen. 

This would still pretty much act like a plugin.
