### ISSUE TITLE
Add requirement chapter in README

### ISSUE THREAD

**Issue by Kaijiro** [shockone/black-screen#401]
Hey,

I was trying to install black-screen on a Windows PC without Python and I ran into an error.
I understood I had to install Python and I did it with the 3.5.1 version but, bad luck, gyp needs Python to be >= 2.5.0 && < 3.0.0

I think you should update your README with the requirement part 

Thank you :)

**Comment by shockone** [comment]
There are no requirements for running the application. Just download and install it from here. https://github.com/shockone/black-screen/releases. Unfortunately, Windows is not supported at the moment.
