### ISSUE TITLE
error in run 'node download-chromedriver.js'

### ISSUE THREAD

**Issue by nkuflk** [shockone/black-screen#402]
System: OS X 10.11.4
Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

Tell the author that this fails on your system:
npm ERR!     node ./download-chromedriver.js

**Comment by nkuflk** [comment]
look like a download error
My console log:
Download failed: socket hang up
black-screen@0.0.1 /Users/flk/code/black-screen
└── UNMET PEER DEPENDENCY typescript@1.9.0-dev.20160525-1.0

**Comment by gholtslander-va** [comment]
Updating to Node 6.2.0 resolved this for me.
