### ISSUE TITLE
Use a persistent shell instead of spawning new commands

### ISSUE THREAD

**Issue by jimmyhmiller** [shockone/black-screen#41]
I was working on adding the ability to call [zsh functions](https://github.com/jimmyhmiller/black-screen/tree/feature/functions) when I noticed that each time a command is run a [new process](https://github.com/shockone/black-screen/blob/master/src/Invocation.ts#L56) is created rather than sending text to additional shell.

One of the functions I use all the time is [autojump](https://github.com/wting/autojump). But unfortunately it isn't much use in black screen because spinning up a new zsh instance and changing directories there doesn't really help. I also noticed this current design prevents settings variables and using them in later commands.

I'm just getting familiar with the code base and so I may be misunderstanding. I'm also sure that there is a good reason for the current way it is done. But just wanted to get discussion started around the topic.

Again, love the idea and seems so far to be a really well made project.

**Comment by shockone** [comment]
@jimmyhmiller, are you aware that Black Screen uses its own shell? If so, I'm not sure what would you do with ZSH functions.

**Comment by jimmyhmiller** [comment]
I wasn't aware of that. I was looking at the project as more just a modern interface into existing shells. But I guess I misunderstood.
