### ISSUE TITLE
Strange display issue in Ranger fm

### ISSUE THREAD

**Issue by sayingandparsing** [shockone/black-screen#411]
I encountered problem when trying to use the ncurses file manager ranger. The interface appears normally after initialization, but when I shift the selection down by one, the entries above, below and adjacent to the newly selected disappear from view. Down again, and about the next 20 or so in the center column vanish; next time, some reappear, often offset from the original location. Heres some pictures:
![down one](https://cloud.githubusercontent.com/assets/12878813/15631105/7952298c-251c-11e6-8260-abfae3996007.png)
![down two](https://cloud.githubusercontent.com/assets/12878813/15631107/81505708-251c-11e6-8148-7d8d0657288c.png)
![deepinscreenshot20160528214918](https://cloud.githubusercontent.com/assets/12878813/15631130/1376d020-251e-11e6-93be-0b599ad599d5.png)

The complete view is restored when I shift to a different column, but entries continue to flicker in and out of sight as I change the selection.
I'm really impressed and excited by black screen and want to use it more, but unfortunately I'm very dependent on ranger.
Does anyone have ideas about what could be the origin of the problem, or how it might be addressed?

**Comment by shockone** [comment]
Hi, @sayingandparsing. It's happening because I wrote my own implementation of ANSI codes support, and it's not complete yet. Will improve in the future.

**Comment by sayingandparsing** [comment]
Okay. Thanks for the update shockone.
I really like the graphical flexibility of atom, but prefer to work in a terminal. Black screen is the perfect solution. Keep up the good work.

**Comment by shockone** [comment]
@sayingandparsing, should work in v0.0.13.
