### ISSUE TITLE
Call app on button click 

### ISSUE THREAD

**Issue by yarossia** [shockone/black-screen#412]
Let us decide can we made call app as in iTerm2 just click setted button and terminal will be opened from tray

**Comment by shockone** [comment]
I'm not sure I understand what it means. A global shortcut that would open the app?

**Comment by yarossia** [comment]
@shockone yes, from tray, programm shoud be runned in tray. For example i click "~" button and window with terminal will be opened

**Comment by shockone** [comment]
Won't implement. You can use plethora of third party tools to bind a global shortcut.
