### ISSUE TITLE
Ctrl+C breaking the tab

### ISSUE THREAD

**Issue by vicodinchik** [shockone/black-screen#413]
When some running command is executed and then stopped by Ctrl+C hotkey, the tab became inactive 
![screen shot 2016-05-30 at 01 40 28](https://cloud.githubusercontent.com/assets/6984143/15635388/a75fda4a-2607-11e6-8d5a-8fe822ea6093.png)

**Comment by shockone** [comment]
Any errors in your JavaScript console? (cmd+option+i)

**Comment by vicodinchik** [comment]
@shockone 
`/opt/homebrew-cask/Caskroom/black-screen/0.0.3/Black Screen.app/Contents/Resources/app.asar/node_mo…:44 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.`

**Comment by shockone** [comment]
Fixed in v0.0.12.
