### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by gristel** [shockone/black-screen#418]
Hi all,
what's the best way of knowing when to update black-screen.
And I suppose for now, updating means delete the cloned repo and re-clone?
Thanks!

**Comment by shockone** [comment]
The planned way is for you not to think about it at all: the application should be responsible for self-updating. Meanwhile you can open https://github.com/shockone/black-screen/releases from time to time and download the latest version.

**Comment by gristel** [comment]
Thanks!
Just 1 more question if you don't mind: how long does it take before latest version gets into brew cask?

**Comment by shockone** [comment]
We just set up homebrew cask yesterday. Don't have any predictions because of that.
