### ISSUE TITLE
How to change the shell?

### ISSUE THREAD

**Issue by wernight** [shockone/black-screen#419]
I tried `chsh` and changing the shell before starting Black Screen:

    $ chsh -s $(which bash)
    $ bash
    $ npm start

However after doing that in Black Screen doing `echo $SHELL` still outputs `/bin/zsh`.

Other issues noted that lead to this:

  * Tab not working to auto-complete
  * Directories like `~/Docu` not showing auto-complete
  * aliases not working (notably virtualenvwrapper)
  * ...

**Comment by shockone** [comment]
We get shell name from environment. Something must be wrong with your environment. What's the output of `echo $SHELL` in bash? https://github.com/shockone/black-screen/blob/master/src/utils/Shell.ts#L68-L68

**Comment by gristel** [comment]
So I take it that bash is the preferred shell for black-screen?

**Comment by gbirke** [comment]
I normally work with zsh and it gets passed on from the regular Mac OS X Terminal app just fine.

**Comment by shockone** [comment]
I use ZSH, and it should work with Black Screen.

**Comment by shockone** [comment]
@wernight, still doesn't work?

**Comment by sublimino** [comment]
@wernight does the problem persist after logging out and back in? Documented [here](http://stackoverflow.com/a/13046283).

**Comment by wernight** [comment]
I didn't try logging out and back in. I was more wondering how it selects
the shell as it's different from they way it works for normal terminals on
Linux (not Mac).

I've some complex ZSH plugins like a Fish like autocomplete and I wanted to
find why some features are not working.

Le mar. 31 mai 2016 à 11:42, Andrew Martin <notifications@github.com> a
écrit :
