### ISSUE TITLE
Features list

### ISSUE THREAD

**Issue by nickcolley** [shockone/black-screen#42]
Be cool to have a list of features that set this apart from your average terminal.

**Comment by shockone** [comment]
Will do.

**Comment by xyc** [comment]
How about a package/plugin system?

**Comment by shockone** [comment]
@xyc, yes, we plan to have plugins. https://github.com/black-screen/black-screen/issues/48#issuecomment-138556130

**Comment by xyc** [comment]
@shockone great to hear that!
