### ISSUE TITLE
Add git auto complete

### ISSUE THREAD

**Issue by thomasbritton** [shockone/black-screen#428]
I think this would be a great addition so it would auto complete branch names etc

**Comment by ashyon** [comment]
Shouldn't it take this from the bash-completion package?

**Comment by thomasbritton** [comment]
Doesn't seem to be working for me, but when I use standard iTerm it autocompletes

**Comment by psimyn** [comment]
seems to work for me

do you have [git-completion](https://github.com/git/git/blob/master/contrib/completion/git-completion.bash) installed/available?

And is 'standard iTerm' the `Terminal` application (built-in) or iTerm2/3?

**Comment by thomasbritton** [comment]
I do have git-completion installed and by standard iTerm I meant the iTerm application sorry 😄

**Comment by iDams** [comment]
@thomasbritton Seems to work for me too (v 0.0.3)
![capture d ecran 2016-06-02 a 12 20 02](https://cloud.githubusercontent.com/assets/1591702/15741962/6ea9a020-28bc-11e6-8cdf-1125ca1118bf.png)

**Comment by thomasbritton** [comment]
Ah!

It's not picking up my aliases in my `.gitconfig` 

I'd normally use the following to switch branch: `git co <branchname>`

So I guess it would be nice for Black Screen to potentially reference any git aliases if possible but not essential.

**Comment by iDams** [comment]
I think it would be simpler to be able to create your own shortcut in a `.blackscreen.config.js` or something like and to link `git co` to `git checkout`?

**Comment by shockone** [comment]
@thomasbritton, that's a good idea, we'll definitely implement it.
@iDams aliases can't consist of two words.

**Comment by shockone** [comment]
@thomasbritton, thanks to @ekaragodin git aliases are now supported. Check it out!

![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/gzr_to00.png)
