### ISSUE TITLE
ls command show unformatted text

### ISSUE THREAD

**Issue by G07cha** [shockone/black-screen#44]
This is how `ls` command looks in Black Screen
![screen shot 2015-09-07 at 9 52 01 am](https://cloud.githubusercontent.com/assets/6943514/9710751/423f9d5e-5546-11e5-8b21-e7047af15efe.png)
And this is how same command looks in Term2(Default Terminal also displays same)
![screen shot 2015-09-07 at 9 52 14 am](https://cloud.githubusercontent.com/assets/6943514/9710752/4242c2cc-5546-11e5-81a8-8f29b033766e.png)

As you can see no formating provided currently.

App builded using `npm run package`
OS X: 10.10.5
Commit: cf8880202fa968b77c631076c215f2ea11ee66bc

**Comment by shockone** [comment]
Could you please press cmd + d to enable debug output, then open the js console, execute ls and show us the output?

**Comment by G07cha** [comment]
CMD + D don't worked for me so I've opened development tools and run command.
Most of the errors `Couldn't write a special char '	' with char code 9.` so this is probably main problem

![Full error log](http://pastebin.com/du7SV71Y)

**Comment by shockone** [comment]
@G07cha, can you try again with the latest master?

**Comment by G07cha** [comment]
Outputs only first item in list
`RangeError: Maximum call stack size exceeded`

**Comment by shockone** [comment]
Could you share the ls binary you use? It would be easier to debug this way.

**Comment by G07cha** [comment]
![Binary](https://app.box.com/s/qakhei57iifmdoiaijlnrk3zbankf16y)

**Comment by shockone** [comment]
@G07cha, the link doesn't work.

**Comment by G07cha** [comment]
@shockone, this is becouse of github redirect, updated comment

**Comment by alebcay** [comment]
I'm also getting some other weird stuff with `ls` coloring and formatting. This is what I get when I run it through `gulp` - everything works the way it should:

![q4ysyk9](https://cloud.githubusercontent.com/assets/3536482/9716672/122cb87e-553a-11e5-9c27-b2f803f10940.png)

but then, when I do `npm run package` and run it from the standalone app bundle, I get this:

![af2jiml](https://cloud.githubusercontent.com/assets/3536482/9716694/49148df8-553a-11e5-9ba8-e489cda46fd2.png)

It seems that the `gulp` version is reading my path - `which ls` returns my `ls` that I installed from MacPorts. However, the standalone doesn't seem to do that, and is instead using `/bin/ls`. Even so, I still can't figure out why it's only outputting the first line out output with `/bin/ls` (it only shows "Applications", nothing else).

**Comment by shockone** [comment]
@G07cha, fixed.

**Comment by shockone** [comment]
@alebcay, I've created a new issue for this because they're technically unrelated. https://github.com/shockone/black-screen/issues/50

**Comment by G07cha** [comment]
Unfortunatly I've still expecting same issue as after first fix, only first file has been shown in list if use `ls` command, but `ls -lA` actually works pretty well.

**Comment by G07cha** [comment]
Confirm, thank you, @shockone
