### ISSUE TITLE
Windows: switch from pty.js to ptyw.js

### ISSUE THREAD

**Issue by luckcolors** [shockone/black-screen#440]
Please switch from https://github.com/rprichard/winpty to
https://github.com/iiegor/ptyw.js.
A few reason why this can be usefull to do:
1. orginal pty.js seems unactive.
2. orginal ptyw.js builds succefully while pty.js does not (builds with visualstudio).

**Comment by shockone** [comment]
Won't implement: Windows is not supported at the moment.
