### ISSUE TITLE
Add icon to window heading

### ISSUE THREAD

**Issue by G07cha** [shockone/black-screen#45]
![screen shot 2015-09-07 at 9 59 09 am](https://cloud.githubusercontent.com/assets/6943514/9710861/24b696a6-5547-11e5-9c4a-c4043bb9c8a8.png)
![screen shot 2015-09-07 at 9 59 54 am](https://cloud.githubusercontent.com/assets/6943514/9710868/3867a960-5547-11e5-8451-01e8b6fe7466.png)

OS X: 10.10.5
Commit: cf8880202fa968b77c631076c215f2ea11ee66bc

**Comment by shockone** [comment]
Could you please do that? I would really appreciate a pull request.

**Comment by G07cha** [comment]
This is my first experience with electron but I'll try to do something and send pull request if I succeed

**Comment by shockone** [comment]
@G07cha, thank you for the effort. Unexpectedly the project became popular, and I'd really use some help.

**Comment by G07cha** [comment]
Sure, I'm glad to be helpful if it possible in open-source projects.

**Comment by shockone** [comment]
It seems that the interface guidelines don't recommend to put the icon into the title bar. And I haven't seen it in other applications. I think it's not worth doing.

https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/WindowNaming.html#//apple_ref/doc/uid/20000957-CH35-SW1

**Comment by G07cha** [comment]
Yep I've tried to find solution but adding icon to BrowserWindow and applying favicon to index.html don't do anothing. Assuming your comment with my opinion we have two ways:
1. [Completly hide titlebar](https://github.com/atom/electron/blob/master/docs/api/frameless-window.md)
2. Try to find the way to hide icon

**Comment by shockone** [comment]
Ah, I must have misunderstood you. I've added the directory icon on purpose https://github.com/shockone/black-screen/blob/master/src/Terminal.ts#L64-L64. It's a standard OS X idiom: if you right click on it, you'll see a path to the current folder. Also, you can open that folder in Finder this way.

Check this out: if I'm in the home directory, it shows a little house icon.
https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/ck-bpuym.png

**Comment by G07cha** [comment]
Not sure that we need this functionality but I only have default folders with specific icons so as another way we can use titlebar to display current status instead of 'Black screen' title and change icon too, or we can just close this issue if this is confirmed feature.

**Comment by shockone** [comment]
Let's close it, if you don't mind. It's not that important, after all.
