### ISSUE TITLE
Cannot cd (change directory) to directory with name that contains spaces

### ISSUE THREAD

**Issue by adchilds** [shockone/black-screen#454]
Using the latest code on master, I cannot cd to a directory that contains spaces in it's name.

For example, if my current working directory is /Users/adchilds/Desktop/ and I have a directory inside my cwd named "Desktop Items" I receive an error saying this directory cannot be found. See the following screenshot:

<img width="1462" alt="cd_directory_with_space" src="https://cloud.githubusercontent.com/assets/1317452/15767081/d66a24fc-290a-11e6-99a5-100d9839a032.png">

This looks to be caused by the fact that when we parse the path in the Common#resolveFile function, we're preserving escape characters such as \ in the path when we really should be getting rid of them.

I have a fix and want to submit a pull-request for this but would appreciate some scrutiny since I'm not entirely familiar with how this may affect the application as a whole.

Thank you!

**Comment by shockone** [comment]
Fixed.
