### ISSUE TITLE
I can not run command with environment variable

### ISSUE THREAD

**Issue by ekaragodin** [shockone/black-screen#464]
`NODE_ENV=dev npm run build`
```shell
Black Screen: command "NODE_ENV=dev" not found.
```

**Comment by shockone** [comment]
A workaround for now:

```
export NODE_ENV=dev
npm run build
```

**Comment by shockone** [comment]
Blocked by https://github.com/shockone/black-screen/issues/307

**Comment by shockone** [comment]
Fixed by https://github.com/shockone/black-screen/commit/ae2b698eafd412c15530b58724ce535c85b28617
