### ISSUE TITLE
ls command does not work

### ISSUE THREAD

**Issue by fabiantheblind** [shockone/black-screen#47]
when I run `ls` the result is:  

    execvp: No such file or directory

**Comment by kblanks** [comment]
OS X version and commit SHA?

**Comment by fabiantheblind** [comment]
SHA: cf8880202fa968b77c631076c215f2ea11ee66bc
OSX Version: 10.10.5

**Comment by kblanks** [comment]
Hm, I don't get this issue on 10.10.3 with the same commit.

**Comment by fabiantheblind** [comment]
This happend with the packed version only. When I run it with gulp it works fine

**Comment by kblanks** [comment]
The packed version works for you? Weird. #32

**Comment by fabiantheblind** [comment]
Yes it works.

**Comment by fabiantheblind** [comment]
Found the error (I think). I'm using an alias for ls `alias ls='els -G'` to use this tool in terminal https://github.com/AnthonyDiGirolamo/els .  
When disabling it ls works fine in Black Screen.app

**Comment by fabiantheblind** [comment]
I'll close this issue.
