### ISSUE TITLE
"node" not found

### ISSUE THREAD

**Issue by tflx** [shockone/black-screen#485]
I get `command "node" not found.` and `command "npm" not found.` when trying to run node/npm commands
Right now I have node installed via brew but same issue existed on a regular node installation.
Both work fine in Terminal.

Version 0.0.3 and El Capitan 10.11.5

**Comment by CrashyBang** [comment]
Getting `command "brew" no found` could be related.

**Comment by balupton** [comment]
could be related to #475

**Comment by cwhite92** [comment]
Getting a similar problem:
```
Black Screen: command "htop" not found.
```
Works in Terminal and iTerm2. Also getting the problem with `brew`.

**Comment by epallerols** [comment]
This is probably related to the settings you have in your `$PATH` environment variable.

Try to run `echo $PATH` and check the difference between both, you are probably missing the node installation folder.

**Comment by shockone** [comment]
What's the output of `which node` (if it doesn't work, try in your usual terminal) and what's the `echo $PATH` in Black Screen?

**Comment by CrashyBang** [comment]
Path from iTerm: `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`  

Path from Black Screen: `/usr/bin:/bin:/usr/sbin:/sbin`  

Black screen appears to be missing: `/usr/local/bin`  

Should I just echo out the updated `PATH` in my `.bashrc`?

**Comment by tflx** [comment]
Same $PATH output for me. Added /usr/local/bin to PATH worked for me too.
