### ISSUE TITLE
No need to add node_modules to path

### ISSUE THREAD

**Issue by markogresak** [shockone/black-screen#51]
In [`package.json`](https://github.com/shockone/black-screen/blob/master/package.json#L60-L63), you're adding `node_modules/.bin` to path. This is not required, since `npm run [script]` will automatically try to find the binaries in `.bin` folder.

**Comment by iiegor** [comment]
+1 

I think the entire ``PATH=node_modules/.bin:$PATH rm -rf node_modules`` is unnecesary and also makes windows users can't be able to run the script.

**Comment by markogresak** [comment]
Using `rm -rf` is the least of problems that make it unusable on Windows. If you look at the source, it's assuming *nix architecture so making it work on windows would require major refactoring.
