### ISSUE TITLE
Russian characters are not displayed correctly

### ISSUE THREAD

**Issue by jt3k** [shockone/black-screen#512]
![](https://i.imgur.com/yJEpTBj.png)

**Comment by jt3k** [comment]
@shockone
example for filename
```
Абракадабра
Комунизм
Сталин
Путин
Тоталитаризм
```

**Comment by shockone** [comment]
What's the output of `echo $LANG`?

**Comment by Kiura** [comment]
@shockone, I have the same problem, and here is the output:

![image](https://cloud.githubusercontent.com/assets/5522096/16171788/3e4e56e2-3581-11e6-9dd4-8b894c73b886.png)

**Comment by jt3k** [comment]
yepp.   this command returns empty in black-screen.
but in iTerm after echo $LANG i see `ru_RU.UTF-8`

then i enter this
export LANG=ru_RU.UTF-8
and is fix the problem with cyrilic.




and after define

**Comment by jt3k** [comment]
👍
