### ISSUE TITLE
Homebrew: Uh oh, could not figure out how to unpack

### ISSUE THREAD

**Issue by smithrb** [shockone/black-screen#513]
brew cask install black-screen

results:

==> Downloading https://github.com/shockone/black-screen/releases/download/v0.0.3/black-screen-0.0.3-mac.zip
######################################################################## 100.0%
==> Verifying checksum for Cask black-screen
Error: Uh oh, could not figure out how to unpack '/Library/Caches/Homebrew/black-screen-0.0.3.zip'

**Comment by shockone** [comment]
Please execute `brew update` and only then `brew cask install black-screen`.

**Comment by shockone** [comment]
Seems like it's an issue with brew.

https://www.google.com/search?q=Uh+oh%2C+could+not+figure+out+how+to+unpack

**Comment by smithrb** [comment]
Could be, I did the same google search as below.

might be related to use of zip files as best I can tell.

**Comment by Tehnix** [comment]
I'm experiencing this as well currently. Although I am using macOS Sierra, so don't know if that is the culprit?

**Comment by liydu** [comment]
Encountered exact same issue. Also on macOS Sierra.

**Comment by stefanopassador** [comment]
Same issue, on the public beta of macOS Sierra!

**Comment by stefanopassador** [comment]
After a `brew update` and `brew upgrade` the install work!
