### ISSUE TITLE
Issues with Vim and similiar programs

### ISSUE THREAD

**Issue by PaulBGD** [shockone/black-screen#527]
I'm guessing these happen with others, but there's 3 big issues when running programs like Vim and htop:

- arrow keys don't work at all
- function (F1, F2, F3, etc) don't work
- the programs only render to some kind of set size and not the actual size of black screen

![Image](https://i.imgur.com/wNpFSEr.png)
![Image](https://i.imgur.com/zMHpm77.png)

Errors in development console:
```
fs.js:1578 Uncaught (in promise) Error: ENOENT: no such file or directory, realpath '/home/paul/.rvm/rubies/default'(…)
fs.js:1578 Uncaught (in promise) Error: ENOENT: no such file or directory, realpath '/home/paul/.rvm/rubies/default'(…)
```

This is on Linux.

**Comment by shockone** [comment]
Should work in v0.1.18.
