### ISSUE TITLE
Invalid symlinks are breaking autompletion

### ISSUE THREAD

**Issue by viktomas** [shockone/black-screen#533]
As soon as there is a invalid symlink in `home` folder or in current folder, the autocompletion doesn't work.

Can be simulated on master (v 0.1.5).

Way to reproduce:
in your home directory run `ln -s non-exiting-file broken-symlink`
tada, the whole autocompletion is broken.

Logs:
Very mysterious message comming from compiled `PromptComponent`:
/home/vicek/workspace/black-screen/compiled/src/views/4_PromptComponent.js:5 Uncaught (in promise) Error: ENOENT: no such file or directory, stat '/home/vicek/broken-symlink'
    at Error (native)

Way to fix:
In https://github.com/shockone/black-screen/blob/87b577b5692867bebbafac483473dd5e292239a4/src/utils/Common.ts#L63 either check if file exists or not reject on error (it's not resilient to drop the whole autocompletion because of one dodgy file)

**Comment by viktomas** [comment]
I'd like to create a PR for this issue but I wonder if there's any strategy for making `black-screen` dependent on new test libraries (I'd like to test the `statsIn` method with `mock-fs` module).

**Comment by shockone** [comment]
@viktomas, thank you for reporting this bug. You can just do `npm i --save-dev mock-fs` (you'd have to install this one too to get typings https://www.npmjs.com/package/@types/mock-fs). Actually, you can just as well skip tests at all.

I'm more interested in how you propose to fix it. I think I'd just change the `fs.stat` call to https://nodejs.org/api/fs.html#fs_fs_lstat_path_callback and that's it.

**Comment by viktomas** [comment]
@shockone: if you are ok with me including the dependency, I'd rather write the test :smiley:.

My idea on solving the bug was check for file existence before calling `fs.stat` here https://github.com/shockone/black-screen/blob/87b577b5692867bebbafac483473dd5e292239a4/src/utils/Common.ts#L63

**Comment by shockone** [comment]
Sure, you can include it.

One question, though: what to do if the file does not exist? You'd either need to narrow the domain of the function to accept only existing files, or widen its codomain to return something like `Maybe<fs.Stats>`.

**Comment by viktomas** [comment]
I had similar thought process. My hacky "attempt" on fixing it which was to log error here

https://github.com/shockone/black-screen/blob/87b577b5692867bebbafac483473dd5e292239a4/src/utils/Common.ts#L65

and then resolving with `resolve()` worked.

What do you think about using lstat instead of stat? http://man7.org/linux/man-pages/man2/lstat.2.html the only difference is that it would return stats of the link instead of the files that the link refers to.

**Comment by shockone** [comment]
Lstat sounds good. :) https://github.com/shockone/black-screen/issues/533#issuecomment-228621721

**Comment by viktomas** [comment]
Next time I'll click through to the links 😊
