### ISSUE TITLE
Stop working after system error

### ISSUE THREAD

**Issue by doberbeatz** [shockone/black-screen#547]
After any system errors, the app stops working and the input filed is lost

http://joxi.ru/E2pb6qGsBEBawr

**Comment by shockone** [comment]
What version are you using?

**Comment by shockone** [comment]
Should work in the latest one.

![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/z3qq87ol.png)

**Comment by doberbeatz** [comment]
I’ve used 0.1.6.203 version

Thanks for fixing :-)
App is awesome, but if it could split display as well as iterm horizontally and vertically it would be very cool!
Thanks.
