### ISSUE TITLE
Open images/html files inline?

### ISSUE THREAD

**Issue by Vatyx** [shockone/black-screen#558]
I had the idea of having a built in command that could open images or render html/md files in line in the terminal considering it is built in electron. How does that sound?

**Comment by shockone** [comment]
Please vote, guys, but I've never ever in my life had a need to view images in a terminal. Personally, it sounds more cool than it is useful.

**Comment by Vatyx** [comment]
I many times wished I could open an image inline in a terminal, especially
when doing image processing.

If I make it, could I PR it?

**Comment by shockone** [comment]
Sure! Take a look at the `PluginManager.registerOutputDecorator` function. It's made exactly for this purpose.

**Comment by darol100** [comment]
I kinda see the value of this specially if this can work from a remote server. Its something in unusual because we are not use to do something like this.
👍

**Comment by Vatyx** [comment]
How does this look?
![imageedit_4_3942727562](https://cloud.githubusercontent.com/assets/7674163/16628231/b64ed6f2-4365-11e6-967b-5904d8cd65c7.png)

I would like this command to automatically be decorated instead of hitting the button each time and also be able to show multiple images at once.

**Comment by shockone** [comment]
How would I, as a new user of Black Screen, know there is a command called `show`?

**Comment by Vatyx** [comment]
You wouldn't with how black screen is set up right now. You call black screen the IDE of terminals. With every IDE there would be more commands beyond what you see in the IDE initially.

Should I change the command? How can I make it obvious? Do you want there to be a list of inbuilt commands that people can be referenced?

**Comment by shockone** [comment]
I don't know the answer; it's an open question, and having a new command might be the way to go. I just believe that it's hard to discover, therefore very few people will benefit from it.

**Comment by shockone** [comment]
By the way, there is already a command that prints a file: `cat`. We could write a decorator for it which would be applicable only to images. But still, not knowing about this feature beforehand, nobody in his right mind will `cat` an image.

**Comment by Vatyx** [comment]
At the same time I don't know `git dff` can be decorated. I don't even know what "decorated" is as a new user. I don't even know how to make tabs, if there are tabs in black screen.

I think there should be some sort of "Welcome to Black Screen" page that pops up when first starting which gives a run down of what features Black Screen has built into it. I can see there being a lot of other inbuilt commands that can utilize the fact that the terminal is running in electron.

With `cat`, I don't think it makes too much sense with what the command is intended for. The expected behavior would be to print the binary of the image. If I `cat`'d a .md file, I wouldn't expect it to render, I would just expect the contents of the file.

**Comment by shockone** [comment]
It's different with git diff: even without knowing about this decorator, you'll still execute this command to show a diff and will discover that it looks better than usual (or worse :-). If you don't like it, you can click the magic wand and see the standard output (you may argue here that it's not obvious you can press this magic want). The same with cat: if you don't like the decoration, you can disable it.

As of tabs, there might be room for improvement, like create a menu option Tab -> Add or something.

**Comment by shockone** [comment]
Actually, an ability to just cat a minimized JSON file and have it nicely printed was the reason I started this project. Goals have changed since then, though.

**Comment by shockone** [comment]
Now I think we should go with `cat`, if you don't have objections. This way you'd just need to know that cat'ing an image can render it, as oppose to knowing that + remembering the command name of a new command with `show`. To help discoverability, I'll add a new screenshot to `README.md`.

What do you think?

**Comment by Vatyx** [comment]
That all makes sense. I do think decorating is not obvious until you
realize it's there.

I do think decorating by default should be on rather than having it toggle.
I don't see much reason for it to not be.

Specifically with show though, I think it's too awkward for having `cat`
produce an image just because as programmers, we aren't used to `cat`
having that effect like you said. Having showing an image be it's own
command makes the commands completely independent and has less of a chance
of being counter intuitive. Your main problem is discoverability, and
depending on how far you are taking this project there might be many
problems with that, but I think that can be easily remedied with a inbuilt
intro/tutorial page.

**Comment by Vatyx** [comment]
But you might still be right, and just tying this feature to one command would be best. This could also translate to cating markdown files and html

**Comment by shockone** [comment]
The only reason it's disabled by default is because it's buggy. :)

**Comment by Vatyx** [comment]
I missed the last thing you said. Let's go with cat. I'll try and get a
commit with rendering an image with cat and then try markdown and html.

Also what's the shortcut for creating a new tab?

**Comment by shockone** [comment]
It's cmd+tab, as everywhere on macOS. By the time Linux is supported, it'll be ctrl+tab on Linux, as everywhere on Linux.

You'd need to add a field `preventDefault: boolean` to `interface OutputDecorator` in order to avoid actually cat'ing an image, because it'd take quite some time. Also, please enable decorators by default. Actually, this flag will break disabling the decorator, but it's fine for the time being.

**Comment by shockone** [comment]
By the way, how hard would it be to add videos support?

**Comment by Vatyx** [comment]
It should be just a matter of using <video></video> tags _I think_. I can try it out shortly but that seems like a cool idea as well.

As for the `preventDefault: boolean`, since decorating is on by default, will it still actually cat an image? Isn't all I need to do is change up the `executors` dictionary to check for cat and to see if the argument is an image/md/etc. and then don't do it the actual command and just let the decorator run?

**Comment by shockone** [comment]
Currently it will execute a command no matter what's the state of a decorator.

**Comment by shockone** [comment]
Alright, it's harder than I thought. Just adding this flag won't be enough; you'd need to add some code to `Job.execute()` in order to actually prevent it's execution. And then it messes up job statuses. 

It seems like preventing execution isn't a good idea after all. Let's get back to the `show` command, shall we? Sorry about that.

**Comment by Vatyx** [comment]
Sure that sounds fine. Do you want to name it `show`? Would something like `preview` or `render` be more descriptive?

**Comment by shockone** [comment]
Show sound fine.

**Comment by darol100** [comment]
`show` sounds good.

**Comment by Vatyx** [comment]
@shockone Do you go on Gitter often? I would like to discuss this further.

**Comment by ashyon** [comment]
I don't think we should use cat. I use it for image stuff, so this would mess up my workflow.
