### ISSUE TITLE
Unable to use "thefuck" app

### ISSUE THREAD

**Issue by spuyet** [shockone/black-screen#569]
![screen shot 2016-07-07 at 5 28 58 pm](https://cloud.githubusercontent.com/assets/5107181/16658916/6fdd58fc-4468-11e6-9e7c-eb1c325f64bd.png)

https://github.com/nvbn/thefuck

**Comment by sg-s** [comment]
did you set your path correctly?

**Comment by shockone** [comment]
Functions currently do not work.

**Comment by spuyet** [comment]
It's on the roadmap ?

Thanks for your work, it's a nice app.

**Comment by shockone** [comment]
It will be handled before the 1.0 release one way or another. Thank you for your kind words, @spuyet.
