### ISSUE TITLE
App stuck after an error

### ISSUE THREAD

**Issue by spuyet** [shockone/black-screen#570]
After a failed `ls`, the terminal stays stuck.
![screen shot 2016-07-07 at 5 32 57 pm](https://cloud.githubusercontent.com/assets/5107181/16659100/0b8b2928-4469-11e6-92e1-364f71bdac82.png)

**Comment by joshuaegclark** [comment]
Can also reproduce this issue by passing an invalid argument to a command like: `git foo` will have the same error and behavior of needing to kill the tab and open a new one to continue using.

**Comment by fuerstberger** [comment]
got the same problem. invalid argument -> terminal stuck.

**Comment by lbenie** [comment]
got the same problem when an error is thrown the app just freezes

**Comment by varunest** [comment]
+1 App freezes sometimes when terminal throws an error.

**Comment by lukeed** [comment]
👍 Happens to me after I run `git status` in a non-git repo. 

I need to open a new tab to continue close the original. That said, I have to <kbd>Click</kbd> on the non-responsive tab in between each keybind:

`git status`, <kbd>Click</kbd>, <kbd>CMD</kbd><kbd>t</kbd>, <kbd>CMD</kbd><kbd>1</kbd>, <kbd>Click</kbd>, <kbd>CMD</kbd><kbd>w</kbd>

**Comment by darol100** [comment]
![message-issue](https://cloud.githubusercontent.com/assets/6808460/16676611/ec4cb50a-4480-11e6-8e65-a179cdd07b73.gif)


It seem like I got the same issue when I use `grep`.

**Comment by darol100** [comment]
I can confirm that this is been fixed already if you are using the git version of the project. Rather than the hombrew version. Shall we close this issue ?

Download the Dev version and you will not run into this issues.

**Comment by nyaaao** [comment]
just for the record:
I've submitted version 0.1.23 (latest as of this writing) to homebrew. PR: [#22695](https://github.com/caskroom/homebrew-cask/pull/22695)

**Comment by nyaaao** [comment]
the PR has landed, so we all can do `brew cask install black-screen --force` and be done with it

**Comment by spuyet** [comment]
Works well now, thanks !
