### ISSUE TITLE
App blocked after using command wrongly

### ISSUE THREAD

**Issue by germtb** [shockone/black-screen#579]
After using certain commands wrongly (try `git`) the app gets blocked and a restart seems to be the only solution.

<img width="1564" alt="screen shot 2016-07-08 at 12 03 29" src="https://cloud.githubusercontent.com/assets/5736690/16685600/141ca38c-4504-11e6-882b-e4718bac4f2f.png">

**Comment by darol100** [comment]
This is a duplicated of https://github.com/shockone/black-screen/issues/570. Shall we close this issue ?

**Comment by darol100** [comment]
I can confirm that this is been fixed already if you are using the git version of the project. Rather than the hombrew version. Shall we close this issue ?

**Comment by nyaaao** [comment]
just for the record:
I've submitted version 0.1.23 (latest as of this writing) to homebrew. PR: [#22695](https://github.com/caskroom/homebrew-cask/pull/22695)

**Comment by nyaaao** [comment]
the PR has landed, so this can be safely closed, I guess

**Comment by shockone** [comment]
Thank you, @nyaaao.
