### ISSUE TITLE
ssh not working with usual syntax

### ISSUE THREAD

**Issue by KuroAku** [shockone/black-screen#599]
If I put:
    `ssh user@the.server`
Returns
    `ssh: Could not resolve hostname user: nodename nor servname provided, or not known`

But, if I use
    `ssh -l user the.server`
it works as expected.

**Comment by gman29** [comment]
Experiencing the same issue as above.

**Comment by shockone** [comment]
Should work in v0.1.32 (will be published in a few minutes).

**Comment by KuroAku** [comment]
Ty for the fast response

**Comment by gman29** [comment]
Awesome thanks!
