### ISSUE TITLE
White block with scroll on the right side of the window

### ISSUE THREAD

**Issue by frenchbread** [shockone/black-screen#612]
Pulled changes from latest `master` & noticed white block with scrollbar on the right side of the terminal window. Is that a feature?

![screen shot 2016-07-14 at 11 33 58](https://cloud.githubusercontent.com/assets/2122679/16833265/31dd63fe-49b7-11e6-9b04-92fce2dbfd7d.png)

**Comment by shockone** [comment]
It is not.

**Comment by bananu7** [comment]
Also happens for me on 10.11.5.

**Comment by shockone** [comment]
Please specify the version you use.

**Comment by bananu7** [comment]
It was 0.1.36, which was what `brew` installed automatically. On the newest snapshot it seems fixed.
