### ISSUE TITLE
The command line has unwanted ligatures in it

### ISSUE THREAD

**Issue by bananu7** [shockone/black-screen#615]
Here's how it looks in action:

<img width="237" alt="screen shot 2016-07-17 at 13 04 09" src="https://cloud.githubusercontent.com/assets/2399997/16900227/35871684-4c1f-11e6-9822-61f2ade46238.png">

I didn't gather debug logs because I don't think they are necessary.

**Comment by shockone** [comment]
Hi, @bananu7. The "unwanted" part is questionable. I added them to show the programming ligatures supported by some fonts, e.g. https://github.com/tonsky/FiraCode. But I'm not saying we absolutely need them enabled, if people vote against, we'll remove them. One thing I'm certain about is that there will be no preference to optionally enable them.

Please vote. Thumb up - support ligatures, thumb down - don't support.

**Comment by bananu7** [comment]
@shockone I think the ligature control options have some nice tweaking capabilities, allowing ligatures such as `fi` or `ffi` to be disabled, while still retaining the ones supported by e.g. FiraCode. I was unable to make such a change because of the type definition regarding `WebkitFontFeatureSettings`. I can try to fiddle around that and see whether it could be improved somehow.

All in all, though, for *the prompt line specifically*, I think that disabling them altogether is a better option that will reduce confusion esp. when copy-pasting the commands. Other areas will probably require more thought.

**Comment by shockone** [comment]
You've made me change my mind. Will remove them.
