### ISSUE TITLE
Copy paste removes previously entered text

### ISSUE THREAD

**Issue by anandgraves** [shockone/black-screen#635]
When first entering text

![image](https://cloud.githubusercontent.com/assets/6824459/17055457/20db9006-500d-11e6-8e10-12b973d1a6a0.png)

and then copy paste, the previously entered text will be removed

![image](https://cloud.githubusercontent.com/assets/6824459/17055486/61ad638e-500d-11e6-94ff-e6598c405d61.png)

This happens with version 0.2.8 (0.2.8.364) on OSX 10.10.5.

**Comment by levin-ilya** [comment]
+1
