### ISSUE TITLE
Integration black-screen as an Atom plugin (terminal tab)

### ISSUE THREAD

**Issue by MoOx** [shockone/black-screen#64]
Hi,

First of all, what you did here looks awesome.
Currently I like to use some terminal tab directly in Atom.app. I found it's nice to be able to edit files as well as seeing possible logs of a running dev server (I am a front-end developer).
So I use [atom-term2](https://github.com/webBoxio/atom-term2) as an Atom plugin to do that atm. For many reasons, this plugin if full of bugs.

I have to admit I am pretty impressed by this "black-screen" project and would like to know if you think it will be possible somehow to integrate this app as an atom plugin to use black-screen as tabs (I didn't take a look to the code yet and I am very new to Electron).

**Comment by G07cha** [comment]
Hi,

The short answer is no, we don't want to port black-screen as plugin for Atom.

Details in #40

**Comment by MoOx** [comment]
:/
