### ISSUE TITLE
AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [shockone/black-screen#652]
Would you be interested to provide an [AppImage](http://appimage.org/) for Linux? electron-builder now has support for it that [makes it really easy](https://github.com/electron-userland/electron-builder/issues/504#issuecomment-233170607) to do.

**Comment by probonopd** [comment]
9 thumbs ups and no responses?

**Comment by drew-gross** [comment]
Willing to accept help on this one. I do request that the person who helps out also updates our CI configuration to make the tests also run on linux.

**Comment by probonopd** [comment]
@drew-gross gave it a try but am running into seemingly unrelated issues; can you have a look? My changes are really tiny:
https://github.com/shockone/black-screen/pull/836/files

**Comment by drew-gross** [comment]
Closing this to consolidate discussion in #836
