### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by cosmo1234** [shockone/black-screen#702]
![screen shot 2016-08-16 at 7 29 40 pm](https://cloud.githubusercontent.com/assets/12961966/17711034/e7c69a10-63e7-11e6-88e4-268a26e43af7.png)

**Comment by mathewmeconry** [comment]
1) Remove node_modules directory completely (rm -rf node_modules).
2) Please ensure that you don't use sudo.
3) npm install.

which node version do you use?

**Comment by drew-gross** [comment]
This looks like it's the same issue that I just fixed in the deploy script.
