### ISSUE TITLE
git-prompt: current diff status

### ISSUE THREAD

**Issue by dmccaffery** [shockone/black-screen#715]
This is my usual prompt:

<img width="536" alt="screen shot 2016-08-25 at 11 25 16 pm" src="https://cloud.githubusercontent.com/assets/1803684/17996042/33df4656-6b1b-11e6-907c-12cf54665e21.png">

black-screen is gorgeous, and I am definitely loving it, but it does hide the default prompt. While it shows the current branch in the bottom right corner, it does not show the current state (diff) like my prompt does.

If you would be able to include the +adds, -deletions, and ~changes somewhere near the git branch label, I could switch to black-screen full-time.

One more question: does black-screen use fira code as the font? I cat'd a file and saw the ligatures. If so... thats just awesome sauce.

For more information on my prompt: https://github.com/pulsebridge/uber

**Comment by dmccaffery** [comment]
I'll look at contributing to this shortly... is there a design doc / approval process?

**Comment by drew-gross** [comment]
No "official" approval process. This looks like a good idea, I'm a little afraid of the status bar getting to busy though.

**Comment by wy193777** [comment]
Just created pull request #840 that implemented this function.
