### ISSUE TITLE
Showing push and pull status in the status bar

### ISSUE THREAD

**Issue by anandgraves** [shockone/black-screen#716]
Showing the push and pull status, e.g. like Sourcetree does, in the status bar, next to the current branch name could be a nice enhancement.

![blackscreen_push_pull_status](https://cloud.githubusercontent.com/assets/6824459/18026666/fd5fb072-6c4e-11e6-8b52-16e2df992c06.png)

**Comment by shockone** [comment]
That's something we definitely want to have.

One suggestions I have is not to use colors. This information isn't important enough to draw attention.

**Comment by drew-gross** [comment]
Done now.
