### ISSUE TITLE
Use of JSDoc for code comments

### ISSUE THREAD

**Issue by mkenne11** [shockone/black-screen#722]
I noticed so far the project doesn't have many inline comments, and with moving towards a 1.0 release wondered if the main authors had considered what comment standard they would use?

JSDoc seems to be the the defacto standard for Javascript/Typescript and has good support in browsers such as VSCode and WebStorm. It also has the advantage of generating HTML documentation.
http://speakingjs.com/es5/ch29.html

**Comment by drew-gross** [comment]
black-screen doesn't expose an API (although it may soon for plugins) so I'm not sure why it would need documentation

**Comment by mkenne11** [comment]
Thanks for responding Drew. The main reason I suggested this issue is that there a few comments within the projects code. Having comments would assist people who would like to contribute understand the code.
The nice thing about jsdoc is a number of popular IDEs recognise this commenting format, and will display information about functions/variables etc in intellisense and tooltips.
It would be nice to have comments especially for exported elements shared by functionality.
Just a thought ....

**Comment by shockone** [comment]
I don't want to impose any restrictions on developers. It's hard as it is to contribute into an unfamiliar project. Making people follow a ten pages list of rules will potentially prevent good contributions for the sake of things I'm not sure we want in the first place.

**Comment by mkenne11** [comment]
No problems @shockone ... that makes sense :)
