### ISSUE TITLE
Nano unusable in Black Screen

### ISSUE THREAD

**Issue by n1889** [shockone/black-screen#73]
Opening a file in nano will result in the viewport being compressed down, with navigation keys adding `(I've found a bug!` to the document.

Attempting to exit the editor is unsuccessful with a "XON ignored" message, and the unmodified keys being added to the document.

![screen shot 2015-09-08 at 09 26 14](https://cloud.githubusercontent.com/assets/385159/9730041/b79fdb0c-560b-11e5-9dfa-3e4f62de9d4b.png)

**Comment by shockone** [comment]
Hey, @n1889. We're working on better ANSI support (that's what makes it look ugly). I'll let you know when it's done.

**Comment by woverton** [comment]
+1

**Comment by woverton** [comment]
I also have an issue with htop

**Comment by shockone** [comment]
Fixed.
