### ISSUE TITLE
v0.2.45 contains v0.2.44 named build file

### ISSUE THREAD

**Issue by Igloczek** [shockone/black-screen#767]
Looks like some versions numbers are not correct, b/c tag version is `v0.2.45`, but file have `0.2.44` in name, so I can't update Cask :<

Current: `https://github.com/shockone/black-screen/releases/download/v0.2.45/black-screen-0.2.44-mac.zip`
Needed: `https://github.com/shockone/black-screen/releases/download/v0.2.45/black-screen-0.2.45-mac.zip`

**Comment by drew-gross** [comment]
Might be an issue with the auto-updater. Lets see if it fixes itself the next time a PR is merged.

**Comment by drew-gross** [comment]
Closed, same as #769
