### ISSUE TITLE
Create homebrew cask for easy installation on Mac

### ISSUE THREAD

**Issue by thom-nic** [shockone/black-screen#77]
Homebrew and its offspring [Caskroom](http://caskroom.io/) are package managers for Mac/ OSX.  Contributing a cask definition would allow Mac users to download and install the app with a single command.  [Here are instructions for creating a cask](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md).  I'd like to do this myself so I'll try to take a shot at it soon but I'll admit I'm not an expert when it comes to creating one.

**Comment by mzgnr** [comment]
I think we need a stable version before that happens.

**Comment by G07cha** [comment]
Hi @thom-nic,
As you can see in [examples](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#examples) of guide that you sended homebrew cask requires builded app so first of all we need as said @mzgnr is to release stable app and then add it to homebrew index.

**Comment by thom-nic** [comment]
You're right, unlike homebrew, Caskroom wants a pkg or dmg or zipped .app file.  So maybe this request is a little early but once you release a snapshot or alpha I'll be happy to take a shot at creating a cask.

**Comment by G07cha** [comment]
Let's keep it open then. Thanks for your contributing, @thom-nic.

**Comment by joshtoo** [comment]
@G07cha - I will get this on the required list for Continuous Delivery post v1.0.0
@thom-nic - The top level issue for anything CI / CD is referenced above and Brew support has been added to the list of deliver requirements.

**Comment by alebcay** [comment]
HI! I'm secretly a maintainer of Homebrew Cask. We can include it in the main repo as soon as you provide a binary release, although I would suggest that some bug fixes go through and wait for the project to stabilize before cutting a release.

Cool project, by the way! I've been following it pretty much all week. :+1:

**Comment by shockone** [comment]
`brew cask install black-screen`.
