### ISSUE TITLE
Cannot perform commands on directories or files with spaces

### ISSUE THREAD

**Issue by jbaskeen** [shockone/black-screen#78]
When a dir or file has a space in the name commands, such as cd or ls, cannot be performed on that directory. Suggestions do not handle the space and manually typing the escape for spaces, i.e. cd My\ New\ Folder/

There are no errors in the dev console associated with this issue.

![image](https://cloud.githubusercontent.com/assets/6549820/9736003/ae2b3886-560c-11e5-9151-6431b344afe7.png)

**Comment by G07cha** [comment]
Thank you, @jbaskeen 
I've done future researching and found that cd `"Developer/Git Projects/"` also ignored by child_pty

**Comment by shockone** [comment]
Fixed.
