### ISSUE TITLE
 Extra space when paste text

### ISSUE THREAD

**Issue by B-lvlax** [shockone/black-screen#816]
When i paste some text it's adds extra lines before and after and sometimes text have the same style that original source(underlined or another color).

![black screen 2016-10-14 12-32-59](https://cloud.githubusercontent.com/assets/16814267/19382811/65028584-920a-11e6-9709-aba7acc279a5.png)

![black screen 2016-10-10 11-52-52](https://cloud.githubusercontent.com/assets/16814267/19230972/1ebe9bda-8ee0-11e6-98ee-f8e700ed33cc.png)

**Comment by drew-gross** [comment]
I have seen this before as well but haven't been able to consistently reproduce it. If you ever discover some consistent repro steps, that would be very useful.

**Comment by B-lvlax** [comment]
For example i copy this line 'brew cask install black-screen' then paste it to the terminal and as result the behavior was the same that described before.

**Comment by B-lvlax** [comment]
And sometimes when i do copy/paste text keep styles from source:
![black screen 2016-10-14 12-30-12](https://cloud.githubusercontent.com/assets/16814267/19382719/191ed64a-920a-11e6-89fb-13f3294f13f8.png)

**Comment by drew-gross** [comment]
When I do that I do see the styles, but not the extra spaces =/

**Comment by B-lvlax** [comment]
Usually i use Safari so extra spaces went  from it. Now i tried doing same things in Chrome and i have got only styled text without spaces.

**Comment by drew-gross** [comment]
Awesome! I can consistently reproduce the issue by using Safari. Thanks a lot for the debugging help!

**Comment by Martin-Andersen** [comment]
I really like "black" but pasting is a pain. I am using safari so I got 10-20 lines surrounding a one line cmd. It would be nice if you could fix it.

A question. How can I remove notifications? I don't need my mac to tell me, that a copy cmd has finished.

Keep up the good work, it's a fresh reproach to a terminal implementation. I like it (-:

**Comment by drew-gross** [comment]
Currently there is no configuration in black-screen, by design, so no features can be turned off. But there is probably somewhere in macOS settings that you can block black-screen from sending notifications.
