### ISSUE TITLE
Website Repo

### ISSUE THREAD

**Issue by mzgnr** [shockone/black-screen#82]
So, before starting coding and designing the website I created a repo and setup Gulp Jekyll and Sass stuff under this url https://github.com/mzgnr/black-screen.github.io.git . If you add me in organization, I'll take care all the web stuff.

**Comment by flawiddsouza** [comment]
I would totally donate a domain name for this project. How does blackscreen.xyz sound?

**Comment by shockone** [comment]
@flawiddsouza, wow, thank you. I've heard cool kind use `.io` nowadays. What do you think?

**Comment by flawiddsouza** [comment]
@shockone Fine with me as long its available.

**Comment by mzgnr** [comment]
It reminded me that Microsoft's domain which is abc.wtf against the Google's abc.xyz :smile: I think io is better. I'm not sure if technically shell/terminal operations are I/O or not.

**Comment by shockone** [comment]
@mzgnr, added. Please do not commit to master without a peer review.

**Comment by mzgnr** [comment]
Oh btw, I'll record a screen cast and working on an animation for website. I think it is going to be cool :)

**Comment by mzgnr** [comment]
@shockone thanks.

**Comment by flawiddsouza** [comment]
@shockone ```.io``` domains seem to be double the cost of ```.com```. What's up with that?

**Comment by qaisjp** [comment]
@flawiddsouza `.io` is cool. that is why.

**Comment by mzgnr** [comment]
@shockone its because of Indian Ocean :smile_cat:

**Comment by flawiddsouza** [comment]
@mzgnr Ha really?

**Comment by mzgnr** [comment]
@flawiddsouza I heard that .io is for Indian Ocean 

![screen shot 2015-09-08 at 20 01 46](https://cloud.githubusercontent.com/assets/6003317/9741701/7ac557ee-5664-11e5-8ffa-c07e833aa098.png)

**Comment by G07cha** [comment]
Guys I think we spending time for useless things, let's thing about domain name when @mzgnr finish a website.
For first time we can just create separate organization's repo and make gh-page for it. What do you think about this?

**Comment by mzgnr** [comment]
@G07cha I'll take care of that after buying coke and cigarette

**Comment by flawiddsouza** [comment]
@G07cha All we've got is time. But I think you might be right.
@mzgnr :smile: 
@shockone .io is definitely on the high range at $50.

**Comment by shockone** [comment]
@flawiddsouza, how about http://black-screen.bs/?

**Comment by onbjerg** [comment]
I have a small web development company with a great designer. Maybe we could mix together a design for the website?

**Comment by shockone** [comment]
Hey, @onbjerg. Sure thing, please collaborate with @mzgnr, he's working on the web-site. And thank you!

**Comment by iiegor** [comment]
![img](http://i.imgur.com/C2fpZXM.png)
[iiegor/black-screen.github.io](https://github.com/iiegor/black-screen.github.io)

**Comment by jdsimcoe** [comment]
@iiegor I like it!

**Comment by shockone** [comment]
I don't think we want a website right now. Having means supporting, and we have more important things to work on.
