### ISSUE TITLE
A web based GUI shell standard

### ISSUE THREAD

**Issue by vilic** [shockone/black-screen#845]
Hi, I am also interested in building a web based GUI shell that's compatible with current character based ecosystem, in TypeScript, but with different interaction details and concept.

While I certainly believe keyboard friendly GUI shell is the future, there are important scenarios to address (like remote session) and it would be really nice if there could be a standard for that.

**Comment by drew-gross** [comment]
I've been thinking about how to handle that kind of thing as well. My rough plan was to have a "context" that black-screen sessions can enter, like "ssh" context or "python interpreter" context. Haven't really fleshed out this idea yet, I have no idea if it will actually work, but I do think we should handle remote sessions somehow.

One advantage of doing it this way is that it would live on top of ssh and not require any additional standards.

**Comment by vilic** [comment]
Actually remote session is one thing. I just noticed the JSON decorator, it seems that the mechanism used by black-screen is not capable of writing interactive GUI console application (with ease). I was hoping that we could have the ability to load a console application like Monaco editor, and this application can be shared cross different shells that implements the standard, and be used from remote as well.

**Comment by drew-gross** [comment]
Check out the `ls` plugin or `git status` plugin. Those are more interactive. It should be totally feasible to make a `monaco` plugin in `black-screen`. You couldn't build a `monaco` program that executes in `black-screen` that displays a GUI though. This is for a lot of reasons, the biggest one being that we delegate execution to an actual shell like `bash` or `zsh`.

I think it might be possible to do what you are suggesting though, having a standard of sorts for GUI console applications. If a "program" is an html file, it can be loaded as an `iframe` if it exists in a specified place and communicates with the parent in a specified way.

**Comment by vilic** [comment]
Yup, that's what I mean, though it is probably not html file. I was thinking something like specific escape sequence in stdout that informs the shell to create webview (which is capable of running in separated threads) for it and then some mechanism to setup the connection between everything.

I'd love to see if you are going to explore another approach besides plugins.

**Comment by drew-gross** [comment]
Ah I see. That does sound like an interesting approach. There are methods for terminals to expose their capabilities to programs running in them, I'd rather have supporting terminals indicate to programs that they have the "show webview" capability, then the program can check for the capability and initiate the handshake if they do, and print "terminal not supported" or something if they don't.

I would be a little hesitant to standardize anything until multiple approaches have been explored, but I would love to watch your implementation to see how it progresses.

**Comment by vilic** [comment]
You are right, it's really just time for brainstorming instead of standardizing for now. And will share my progress if there would be any. (LOL)
