### ISSUE TITLE
Mac Tab bar shows up in black screen

### ISSUE THREAD

**Issue by pmkary** [shockone/black-screen#869]
As in Sierra there is a new option: 

<img width="321" alt="screen shot 2016-11-05 at 7 36 59 pm" src="https://cloud.githubusercontent.com/assets/2157285/20031636/08c2f596-a390-11e6-82e2-ff248dd6f0ea.png">

Which if you enable will result in something like this:

<img width="607" alt="screen shot 2016-11-05 at 7 37 12 pm" src="https://cloud.githubusercontent.com/assets/2157285/20031641/21248064-a390-11e6-8e3c-f5cc54c01d2c.png">

It can be easily fixed by updating the electron.

**Comment by drew-gross** [comment]
Best bug report ever, it even included exactly how to fix the problem :) Thanks! Fixed in #870
