### ISSUE TITLE
Support for imgcat?

### ISSUE THREAD

**Issue by erkkimon** [shockone/black-screen#882]
It would be very useful to be able to see images as images instead of filename listing. With a Node-based solution that would probably be quite easy to show <img src="asdf.jpg" /> instead of just the filename. And it would be nice to be able to print an image into the terminal emulator instead of opening an external application just to make sure that I'm working with the image file I think I'm working with. Does that idea make any sense?

**Comment by drew-gross** [comment]
This is already possible using the `show` command.
